// GENERATED by scripts/gen-i18n-barrel.ts from en/*.json. Do not edit by hand; run `bun run i18n:barrel`.
import account from "./account.json";
import api from "./api.json";
import browse from "./browse.json";
import clay from "./clay.json";
import dashboard from "./dashboard.json";
import device from "./device.json";
import errors from "./errors.json";
import feedback from "./feedback.json";
import footer from "./footer.json";
import home from "./home.json";
import layout from "./layout.json";
import legal from "./legal.json";
import nav from "./nav.json";
import operator from "./operator.json";
import plugin from "./plugin.json";
import pluginDetail from "./pluginDetail.json";
import pluginManage from "./pluginManage.json";
import profile from "./profile.json";
import reports from "./reports.json";
import scope from "./scope.json";

/** The English catalog as a typed value: the source of truth for message keys (see `@/i18n`). */
export default {
  account,
  api,
  browse,
  clay,
  dashboard,
  device,
  errors,
  feedback,
  footer,
  home,
  layout,
  legal,
  nav,
  operator,
  plugin,
  pluginDetail,
  pluginManage,
  profile,
  reports,
  scope,
} as const;
