/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as V1VerifiedRouteImport } from './routes/v1.verified'
import { Route as V1SearchRouteImport } from './routes/v1.search'
import { Route as V1RegistryRouteImport } from './routes/v1.registry'
import { Route as PluginsSplatRouteImport } from './routes/plugins.$'
import { Route as OrgsOrgRouteImport } from './routes/orgs.$org'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalLicensesRouteImport } from './routes/legal.licenses'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'
import { Route as DevelopersIdRouteImport } from './routes/developers.$id'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOrgsRouteImport } from './routes/dashboard.orgs'
import { Route as AuthMeRouteImport } from './routes/auth.me'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthGithubRouteImport } from './routes/auth.github'
import { Route as ApiOrgsRouteImport } from './routes/api.orgs'
import { Route as DashboardPluginsIndexRouteImport } from './routes/dashboard.plugins.index'
import { Route as V1PluginsNameRouteImport } from './routes/v1.plugins.$name'
import { Route as V1DevelopersIdRouteImport } from './routes/v1.developers.$id'
import { Route as DashboardPluginsSplatRouteImport } from './routes/dashboard.plugins.$'
import { Route as DashboardOrgsOrgRouteImport } from './routes/dashboard.orgs_.$org'
import { Route as DashboardAccountTokensRouteImport } from './routes/dashboard.account.tokens'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'
import { Route as ApiPluginsYankRouteImport } from './routes/api.plugins.yank'
import { Route as ApiPluginsVersionsRouteImport } from './routes/api.plugins.versions'
import { Route as ApiPluginsDeprecateRouteImport } from './routes/api.plugins.deprecate'
import { Route as ApiOrgsOrgRouteImport } from './routes/api.orgs.$org'
import { Route as ApiDeviceApproveRouteImport } from './routes/api.device.approve'
import { Route as ApiAccountTokensRouteImport } from './routes/api.account.tokens'
import { Route as ApiAccountProfileRouteImport } from './routes/api.account.profile'
import { Route as V1PluginsNameVersionsRouteImport } from './routes/v1.plugins.$name.versions'
import { Route as V1PluginsNameReviewsRouteImport } from './routes/v1.plugins.$name.reviews'
import { Route as V1PluginsNameReadmeRouteImport } from './routes/v1.plugins.$name.readme'
import { Route as V1PluginsNameCommentsRouteImport } from './routes/v1.plugins.$name.comments'
import { Route as ApiPluginsNameListingRouteImport } from './routes/api.plugins.$name.listing'
import { Route as ApiOrgsOrgScopesRouteImport } from './routes/api.orgs.$org.scopes'
import { Route as ApiOrgsOrgProfileRouteImport } from './routes/api.orgs.$org.profile'
import { Route as ApiOrgsOrgMembersRouteImport } from './routes/api.orgs.$org.members'
import { Route as ApiOrgsOrgIconRouteImport } from './routes/api.orgs.$org.icon'
import { Route as ApiOrgsOrgDomainsRouteImport } from './routes/api.orgs.$org.domains'
import { Route as ApiOrgsOrgDisplayNameRouteImport } from './routes/api.orgs.$org.display-name'
import { Route as ApiAccountTokensHashRouteImport } from './routes/api.account.tokens.$hash'
import { Route as ApiOrgsOrgMembersMemberIdRouteImport } from './routes/api.orgs.$org.members.$memberId'
import { Route as V1PluginsNameVVersionChar91indexChar93RouteImport } from './routes/v1.plugins.$name.v.$version.[index]'
import { Route as V1PluginsNameReviewsReviewIdVoteRouteImport } from './routes/v1.plugins.$name.reviews.$reviewId.vote'
import { Route as V1PluginsNameCommentsCommentIdVoteRouteImport } from './routes/v1.plugins.$name.comments.$commentId.vote'
import { Route as V1PluginsNameVVersionFilesSplatRouteImport } from './routes/v1.plugins.$name.v.$version.files.$'

const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const V1VerifiedRoute = V1VerifiedRouteImport.update({
  id: '/v1/verified',
  path: '/v1/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SearchRoute = V1SearchRouteImport.update({
  id: '/v1/search',
  path: '/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RegistryRoute = V1RegistryRouteImport.update({
  id: '/v1/registry',
  path: '/v1/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSplatRoute = PluginsSplatRouteImport.update({
  id: '/plugins/$',
  path: '/plugins/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgRoute = OrgsOrgRouteImport.update({
  id: '/orgs/$org',
  path: '/orgs/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLicensesRoute = LegalLicensesRouteImport.update({
  id: '/legal/licenses',
  path: '/legal/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIdRoute = DevelopersIdRouteImport.update({
  id: '/developers/$id',
  path: '/developers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrgsRoute = DashboardOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthMeRoute = AuthMeRouteImport.update({
  id: '/auth/me',
  path: '/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/auth/github',
  path: '/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgsRoute = ApiOrgsRouteImport.update({
  id: '/api/orgs',
  path: '/api/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPluginsIndexRoute = DashboardPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => DashboardRoute,
} as any)
const V1PluginsNameRoute = V1PluginsNameRouteImport.update({
  id: '/v1/plugins/$name',
  path: '/v1/plugins/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const V1DevelopersIdRoute = V1DevelopersIdRouteImport.update({
  id: '/v1/developers/$id',
  path: '/v1/developers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPluginsSplatRoute = DashboardPluginsSplatRouteImport.update({
  id: '/plugins/$',
  path: '/plugins/$',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrgsOrgRoute = DashboardOrgsOrgRouteImport.update({
  id: '/orgs_/$org',
  path: '/orgs/$org',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountTokensRoute = DashboardAccountTokensRouteImport.update({
  id: '/account/tokens',
  path: '/account/tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGithubRoute,
} as any)
const ApiPluginsYankRoute = ApiPluginsYankRouteImport.update({
  id: '/api/plugins/yank',
  path: '/api/plugins/yank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsVersionsRoute = ApiPluginsVersionsRouteImport.update({
  id: '/api/plugins/versions',
  path: '/api/plugins/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsDeprecateRoute = ApiPluginsDeprecateRouteImport.update({
  id: '/api/plugins/deprecate',
  path: '/api/plugins/deprecate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgsOrgRoute = ApiOrgsOrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => ApiOrgsRoute,
} as any)
const ApiDeviceApproveRoute = ApiDeviceApproveRouteImport.update({
  id: '/api/device/approve',
  path: '/api/device/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountTokensRoute = ApiAccountTokensRouteImport.update({
  id: '/api/account/tokens',
  path: '/api/account/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountProfileRoute = ApiAccountProfileRouteImport.update({
  id: '/api/account/profile',
  path: '/api/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const V1PluginsNameVersionsRoute = V1PluginsNameVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const V1PluginsNameReviewsRoute = V1PluginsNameReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const V1PluginsNameReadmeRoute = V1PluginsNameReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const V1PluginsNameCommentsRoute = V1PluginsNameCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const ApiPluginsNameListingRoute = ApiPluginsNameListingRouteImport.update({
  id: '/api/plugins/$name/listing',
  path: '/api/plugins/$name/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgsOrgScopesRoute = ApiOrgsOrgScopesRouteImport.update({
  id: '/scopes',
  path: '/scopes',
  getParentRoute: () => ApiOrgsOrgRoute,
} as any)
const ApiOrgsOrgProfileRoute = ApiOrgsOrgProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ApiOrgsOrgRoute,
} as any)
const ApiOrgsOrgMembersRoute = ApiOrgsOrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiOrgsOrgRoute,
} as any)
const ApiOrgsOrgIconRoute = ApiOrgsOrgIconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => ApiOrgsOrgRoute,
} as any)
const ApiOrgsOrgDomainsRoute = ApiOrgsOrgDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ApiOrgsOrgRoute,
} as any)
const ApiOrgsOrgDisplayNameRoute = ApiOrgsOrgDisplayNameRouteImport.update({
  id: '/display-name',
  path: '/display-name',
  getParentRoute: () => ApiOrgsOrgRoute,
} as any)
const ApiAccountTokensHashRoute = ApiAccountTokensHashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => ApiAccountTokensRoute,
} as any)
const ApiOrgsOrgMembersMemberIdRoute =
  ApiOrgsOrgMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => ApiOrgsOrgMembersRoute,
  } as any)
const V1PluginsNameVVersionChar91indexChar93Route =
  V1PluginsNameVVersionChar91indexChar93RouteImport.update({
    id: '/v/$version/index',
    path: '/v/$version/index',
    getParentRoute: () => V1PluginsNameRoute,
  } as any)
const V1PluginsNameReviewsReviewIdVoteRoute =
  V1PluginsNameReviewsReviewIdVoteRouteImport.update({
    id: '/$reviewId/vote',
    path: '/$reviewId/vote',
    getParentRoute: () => V1PluginsNameReviewsRoute,
  } as any)
const V1PluginsNameCommentsCommentIdVoteRoute =
  V1PluginsNameCommentsCommentIdVoteRouteImport.update({
    id: '/$commentId/vote',
    path: '/$commentId/vote',
    getParentRoute: () => V1PluginsNameCommentsRoute,
  } as any)
const V1PluginsNameVVersionFilesSplatRoute =
  V1PluginsNameVVersionFilesSplatRouteImport.update({
    id: '/v/$version/files/$',
    path: '/v/$version/files/$',
    getParentRoute: () => V1PluginsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof DeviceRoute
  '/api/orgs': typeof ApiOrgsRouteWithChildren
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/dashboard/orgs': typeof DashboardOrgsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/developers/$id': typeof DevelopersIdRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/licenses': typeof LegalLicensesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orgs/$org': typeof OrgsOrgRoute
  '/plugins/$': typeof PluginsSplatRoute
  '/v1/registry': typeof V1RegistryRoute
  '/v1/search': typeof V1SearchRoute
  '/v1/verified': typeof V1VerifiedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tokens': typeof ApiAccountTokensRouteWithChildren
  '/api/device/approve': typeof ApiDeviceApproveRoute
  '/api/orgs/$org': typeof ApiOrgsOrgRouteWithChildren
  '/api/plugins/deprecate': typeof ApiPluginsDeprecateRoute
  '/api/plugins/versions': typeof ApiPluginsVersionsRoute
  '/api/plugins/yank': typeof ApiPluginsYankRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/dashboard/account/tokens': typeof DashboardAccountTokensRoute
  '/dashboard/orgs/$org': typeof DashboardOrgsOrgRoute
  '/dashboard/plugins/$': typeof DashboardPluginsSplatRoute
  '/v1/developers/$id': typeof V1DevelopersIdRoute
  '/v1/plugins/$name': typeof V1PluginsNameRouteWithChildren
  '/dashboard/plugins/': typeof DashboardPluginsIndexRoute
  '/api/account/tokens/$hash': typeof ApiAccountTokensHashRoute
  '/api/orgs/$org/display-name': typeof ApiOrgsOrgDisplayNameRoute
  '/api/orgs/$org/domains': typeof ApiOrgsOrgDomainsRoute
  '/api/orgs/$org/icon': typeof ApiOrgsOrgIconRoute
  '/api/orgs/$org/members': typeof ApiOrgsOrgMembersRouteWithChildren
  '/api/orgs/$org/profile': typeof ApiOrgsOrgProfileRoute
  '/api/orgs/$org/scopes': typeof ApiOrgsOrgScopesRoute
  '/api/plugins/$name/listing': typeof ApiPluginsNameListingRoute
  '/v1/plugins/$name/comments': typeof V1PluginsNameCommentsRouteWithChildren
  '/v1/plugins/$name/readme': typeof V1PluginsNameReadmeRoute
  '/v1/plugins/$name/reviews': typeof V1PluginsNameReviewsRouteWithChildren
  '/v1/plugins/$name/versions': typeof V1PluginsNameVersionsRoute
  '/api/orgs/$org/members/$memberId': typeof ApiOrgsOrgMembersMemberIdRoute
  '/v1/plugins/$name/comments/$commentId/vote': typeof V1PluginsNameCommentsCommentIdVoteRoute
  '/v1/plugins/$name/reviews/$reviewId/vote': typeof V1PluginsNameReviewsReviewIdVoteRoute
  '/v1/plugins/$name/v/$version/index': typeof V1PluginsNameVVersionChar91indexChar93Route
  '/v1/plugins/$name/v/$version/files/$': typeof V1PluginsNameVVersionFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/api/orgs': typeof ApiOrgsRouteWithChildren
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/dashboard/orgs': typeof DashboardOrgsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/developers/$id': typeof DevelopersIdRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/licenses': typeof LegalLicensesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orgs/$org': typeof OrgsOrgRoute
  '/plugins/$': typeof PluginsSplatRoute
  '/v1/registry': typeof V1RegistryRoute
  '/v1/search': typeof V1SearchRoute
  '/v1/verified': typeof V1VerifiedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/legal': typeof LegalIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tokens': typeof ApiAccountTokensRouteWithChildren
  '/api/device/approve': typeof ApiDeviceApproveRoute
  '/api/orgs/$org': typeof ApiOrgsOrgRouteWithChildren
  '/api/plugins/deprecate': typeof ApiPluginsDeprecateRoute
  '/api/plugins/versions': typeof ApiPluginsVersionsRoute
  '/api/plugins/yank': typeof ApiPluginsYankRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/dashboard/account/tokens': typeof DashboardAccountTokensRoute
  '/dashboard/orgs/$org': typeof DashboardOrgsOrgRoute
  '/dashboard/plugins/$': typeof DashboardPluginsSplatRoute
  '/v1/developers/$id': typeof V1DevelopersIdRoute
  '/v1/plugins/$name': typeof V1PluginsNameRouteWithChildren
  '/dashboard/plugins': typeof DashboardPluginsIndexRoute
  '/api/account/tokens/$hash': typeof ApiAccountTokensHashRoute
  '/api/orgs/$org/display-name': typeof ApiOrgsOrgDisplayNameRoute
  '/api/orgs/$org/domains': typeof ApiOrgsOrgDomainsRoute
  '/api/orgs/$org/icon': typeof ApiOrgsOrgIconRoute
  '/api/orgs/$org/members': typeof ApiOrgsOrgMembersRouteWithChildren
  '/api/orgs/$org/profile': typeof ApiOrgsOrgProfileRoute
  '/api/orgs/$org/scopes': typeof ApiOrgsOrgScopesRoute
  '/api/plugins/$name/listing': typeof ApiPluginsNameListingRoute
  '/v1/plugins/$name/comments': typeof V1PluginsNameCommentsRouteWithChildren
  '/v1/plugins/$name/readme': typeof V1PluginsNameReadmeRoute
  '/v1/plugins/$name/reviews': typeof V1PluginsNameReviewsRouteWithChildren
  '/v1/plugins/$name/versions': typeof V1PluginsNameVersionsRoute
  '/api/orgs/$org/members/$memberId': typeof ApiOrgsOrgMembersMemberIdRoute
  '/v1/plugins/$name/comments/$commentId/vote': typeof V1PluginsNameCommentsCommentIdVoteRoute
  '/v1/plugins/$name/reviews/$reviewId/vote': typeof V1PluginsNameReviewsReviewIdVoteRoute
  '/v1/plugins/$name/v/$version/index': typeof V1PluginsNameVVersionChar91indexChar93Route
  '/v1/plugins/$name/v/$version/files/$': typeof V1PluginsNameVVersionFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof DeviceRoute
  '/api/orgs': typeof ApiOrgsRouteWithChildren
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/dashboard/orgs': typeof DashboardOrgsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/developers/$id': typeof DevelopersIdRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/licenses': typeof LegalLicensesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orgs/$org': typeof OrgsOrgRoute
  '/plugins/$': typeof PluginsSplatRoute
  '/v1/registry': typeof V1RegistryRoute
  '/v1/search': typeof V1SearchRoute
  '/v1/verified': typeof V1VerifiedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tokens': typeof ApiAccountTokensRouteWithChildren
  '/api/device/approve': typeof ApiDeviceApproveRoute
  '/api/orgs/$org': typeof ApiOrgsOrgRouteWithChildren
  '/api/plugins/deprecate': typeof ApiPluginsDeprecateRoute
  '/api/plugins/versions': typeof ApiPluginsVersionsRoute
  '/api/plugins/yank': typeof ApiPluginsYankRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/dashboard/account/tokens': typeof DashboardAccountTokensRoute
  '/dashboard/orgs_/$org': typeof DashboardOrgsOrgRoute
  '/dashboard/plugins/$': typeof DashboardPluginsSplatRoute
  '/v1/developers/$id': typeof V1DevelopersIdRoute
  '/v1/plugins/$name': typeof V1PluginsNameRouteWithChildren
  '/dashboard/plugins/': typeof DashboardPluginsIndexRoute
  '/api/account/tokens/$hash': typeof ApiAccountTokensHashRoute
  '/api/orgs/$org/display-name': typeof ApiOrgsOrgDisplayNameRoute
  '/api/orgs/$org/domains': typeof ApiOrgsOrgDomainsRoute
  '/api/orgs/$org/icon': typeof ApiOrgsOrgIconRoute
  '/api/orgs/$org/members': typeof ApiOrgsOrgMembersRouteWithChildren
  '/api/orgs/$org/profile': typeof ApiOrgsOrgProfileRoute
  '/api/orgs/$org/scopes': typeof ApiOrgsOrgScopesRoute
  '/api/plugins/$name/listing': typeof ApiPluginsNameListingRoute
  '/v1/plugins/$name/comments': typeof V1PluginsNameCommentsRouteWithChildren
  '/v1/plugins/$name/readme': typeof V1PluginsNameReadmeRoute
  '/v1/plugins/$name/reviews': typeof V1PluginsNameReviewsRouteWithChildren
  '/v1/plugins/$name/versions': typeof V1PluginsNameVersionsRoute
  '/api/orgs/$org/members/$memberId': typeof ApiOrgsOrgMembersMemberIdRoute
  '/v1/plugins/$name/comments/$commentId/vote': typeof V1PluginsNameCommentsCommentIdVoteRoute
  '/v1/plugins/$name/reviews/$reviewId/vote': typeof V1PluginsNameReviewsReviewIdVoteRoute
  '/v1/plugins/$name/v/$version/index': typeof V1PluginsNameVVersionChar91indexChar93Route
  '/v1/plugins/$name/v/$version/files/$': typeof V1PluginsNameVVersionFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/device'
    | '/api/orgs'
    | '/auth/github'
    | '/auth/logout'
    | '/auth/me'
    | '/dashboard/orgs'
    | '/dashboard/profile'
    | '/developers/$id'
    | '/legal/acceptable-use'
    | '/legal/cookies'
    | '/legal/licenses'
    | '/legal/privacy'
    | '/legal/terms'
    | '/orgs/$org'
    | '/plugins/$'
    | '/v1/registry'
    | '/v1/search'
    | '/v1/verified'
    | '/dashboard/'
    | '/legal/'
    | '/plugins/'
    | '/api/account/profile'
    | '/api/account/tokens'
    | '/api/device/approve'
    | '/api/orgs/$org'
    | '/api/plugins/deprecate'
    | '/api/plugins/versions'
    | '/api/plugins/yank'
    | '/auth/github/callback'
    | '/dashboard/account/tokens'
    | '/dashboard/orgs/$org'
    | '/dashboard/plugins/$'
    | '/v1/developers/$id'
    | '/v1/plugins/$name'
    | '/dashboard/plugins/'
    | '/api/account/tokens/$hash'
    | '/api/orgs/$org/display-name'
    | '/api/orgs/$org/domains'
    | '/api/orgs/$org/icon'
    | '/api/orgs/$org/members'
    | '/api/orgs/$org/profile'
    | '/api/orgs/$org/scopes'
    | '/api/plugins/$name/listing'
    | '/v1/plugins/$name/comments'
    | '/v1/plugins/$name/readme'
    | '/v1/plugins/$name/reviews'
    | '/v1/plugins/$name/versions'
    | '/api/orgs/$org/members/$memberId'
    | '/v1/plugins/$name/comments/$commentId/vote'
    | '/v1/plugins/$name/reviews/$reviewId/vote'
    | '/v1/plugins/$name/v/$version/index'
    | '/v1/plugins/$name/v/$version/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/api/orgs'
    | '/auth/github'
    | '/auth/logout'
    | '/auth/me'
    | '/dashboard/orgs'
    | '/dashboard/profile'
    | '/developers/$id'
    | '/legal/acceptable-use'
    | '/legal/cookies'
    | '/legal/licenses'
    | '/legal/privacy'
    | '/legal/terms'
    | '/orgs/$org'
    | '/plugins/$'
    | '/v1/registry'
    | '/v1/search'
    | '/v1/verified'
    | '/dashboard'
    | '/legal'
    | '/plugins'
    | '/api/account/profile'
    | '/api/account/tokens'
    | '/api/device/approve'
    | '/api/orgs/$org'
    | '/api/plugins/deprecate'
    | '/api/plugins/versions'
    | '/api/plugins/yank'
    | '/auth/github/callback'
    | '/dashboard/account/tokens'
    | '/dashboard/orgs/$org'
    | '/dashboard/plugins/$'
    | '/v1/developers/$id'
    | '/v1/plugins/$name'
    | '/dashboard/plugins'
    | '/api/account/tokens/$hash'
    | '/api/orgs/$org/display-name'
    | '/api/orgs/$org/domains'
    | '/api/orgs/$org/icon'
    | '/api/orgs/$org/members'
    | '/api/orgs/$org/profile'
    | '/api/orgs/$org/scopes'
    | '/api/plugins/$name/listing'
    | '/v1/plugins/$name/comments'
    | '/v1/plugins/$name/readme'
    | '/v1/plugins/$name/reviews'
    | '/v1/plugins/$name/versions'
    | '/api/orgs/$org/members/$memberId'
    | '/v1/plugins/$name/comments/$commentId/vote'
    | '/v1/plugins/$name/reviews/$reviewId/vote'
    | '/v1/plugins/$name/v/$version/index'
    | '/v1/plugins/$name/v/$version/files/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/device'
    | '/api/orgs'
    | '/auth/github'
    | '/auth/logout'
    | '/auth/me'
    | '/dashboard/orgs'
    | '/dashboard/profile'
    | '/developers/$id'
    | '/legal/acceptable-use'
    | '/legal/cookies'
    | '/legal/licenses'
    | '/legal/privacy'
    | '/legal/terms'
    | '/orgs/$org'
    | '/plugins/$'
    | '/v1/registry'
    | '/v1/search'
    | '/v1/verified'
    | '/dashboard/'
    | '/legal/'
    | '/plugins/'
    | '/api/account/profile'
    | '/api/account/tokens'
    | '/api/device/approve'
    | '/api/orgs/$org'
    | '/api/plugins/deprecate'
    | '/api/plugins/versions'
    | '/api/plugins/yank'
    | '/auth/github/callback'
    | '/dashboard/account/tokens'
    | '/dashboard/orgs_/$org'
    | '/dashboard/plugins/$'
    | '/v1/developers/$id'
    | '/v1/plugins/$name'
    | '/dashboard/plugins/'
    | '/api/account/tokens/$hash'
    | '/api/orgs/$org/display-name'
    | '/api/orgs/$org/domains'
    | '/api/orgs/$org/icon'
    | '/api/orgs/$org/members'
    | '/api/orgs/$org/profile'
    | '/api/orgs/$org/scopes'
    | '/api/plugins/$name/listing'
    | '/v1/plugins/$name/comments'
    | '/v1/plugins/$name/readme'
    | '/v1/plugins/$name/reviews'
    | '/v1/plugins/$name/versions'
    | '/api/orgs/$org/members/$memberId'
    | '/v1/plugins/$name/comments/$commentId/vote'
    | '/v1/plugins/$name/reviews/$reviewId/vote'
    | '/v1/plugins/$name/v/$version/index'
    | '/v1/plugins/$name/v/$version/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  ApiOrgsRoute: typeof ApiOrgsRouteWithChildren
  AuthGithubRoute: typeof AuthGithubRouteWithChildren
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthMeRoute: typeof AuthMeRoute
  DevelopersIdRoute: typeof DevelopersIdRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalLicensesRoute: typeof LegalLicensesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OrgsOrgRoute: typeof OrgsOrgRoute
  PluginsSplatRoute: typeof PluginsSplatRoute
  V1RegistryRoute: typeof V1RegistryRoute
  V1SearchRoute: typeof V1SearchRoute
  V1VerifiedRoute: typeof V1VerifiedRoute
  LegalIndexRoute: typeof LegalIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  ApiAccountProfileRoute: typeof ApiAccountProfileRoute
  ApiAccountTokensRoute: typeof ApiAccountTokensRouteWithChildren
  ApiDeviceApproveRoute: typeof ApiDeviceApproveRoute
  ApiPluginsDeprecateRoute: typeof ApiPluginsDeprecateRoute
  ApiPluginsVersionsRoute: typeof ApiPluginsVersionsRoute
  ApiPluginsYankRoute: typeof ApiPluginsYankRoute
  V1DevelopersIdRoute: typeof V1DevelopersIdRoute
  V1PluginsNameRoute: typeof V1PluginsNameRouteWithChildren
  ApiPluginsNameListingRoute: typeof ApiPluginsNameListingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/v1/verified': {
      id: '/v1/verified'
      path: '/v1/verified'
      fullPath: '/v1/verified'
      preLoaderRoute: typeof V1VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/search': {
      id: '/v1/search'
      path: '/v1/search'
      fullPath: '/v1/search'
      preLoaderRoute: typeof V1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/registry': {
      id: '/v1/registry'
      path: '/v1/registry'
      fullPath: '/v1/registry'
      preLoaderRoute: typeof V1RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$': {
      id: '/plugins/$'
      path: '/plugins/$'
      fullPath: '/plugins/$'
      preLoaderRoute: typeof PluginsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$org': {
      id: '/orgs/$org'
      path: '/orgs/$org'
      fullPath: '/orgs/$org'
      preLoaderRoute: typeof OrgsOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/licenses': {
      id: '/legal/licenses'
      path: '/legal/licenses'
      fullPath: '/legal/licenses'
      preLoaderRoute: typeof LegalLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/$id': {
      id: '/developers/$id'
      path: '/developers/$id'
      fullPath: '/developers/$id'
      preLoaderRoute: typeof DevelopersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orgs': {
      id: '/dashboard/orgs'
      path: '/orgs'
      fullPath: '/dashboard/orgs'
      preLoaderRoute: typeof DashboardOrgsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/me': {
      id: '/auth/me'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/auth/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orgs': {
      id: '/api/orgs'
      path: '/api/orgs'
      fullPath: '/api/orgs'
      preLoaderRoute: typeof ApiOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/plugins/': {
      id: '/dashboard/plugins/'
      path: '/plugins'
      fullPath: '/dashboard/plugins/'
      preLoaderRoute: typeof DashboardPluginsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/v1/plugins/$name': {
      id: '/v1/plugins/$name'
      path: '/v1/plugins/$name'
      fullPath: '/v1/plugins/$name'
      preLoaderRoute: typeof V1PluginsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/developers/$id': {
      id: '/v1/developers/$id'
      path: '/v1/developers/$id'
      fullPath: '/v1/developers/$id'
      preLoaderRoute: typeof V1DevelopersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/plugins/$': {
      id: '/dashboard/plugins/$'
      path: '/plugins/$'
      fullPath: '/dashboard/plugins/$'
      preLoaderRoute: typeof DashboardPluginsSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orgs_/$org': {
      id: '/dashboard/orgs_/$org'
      path: '/orgs/$org'
      fullPath: '/dashboard/orgs/$org'
      preLoaderRoute: typeof DashboardOrgsOrgRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account/tokens': {
      id: '/dashboard/account/tokens'
      path: '/account/tokens'
      fullPath: '/dashboard/account/tokens'
      preLoaderRoute: typeof DashboardAccountTokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof AuthGithubRoute
    }
    '/api/plugins/yank': {
      id: '/api/plugins/yank'
      path: '/api/plugins/yank'
      fullPath: '/api/plugins/yank'
      preLoaderRoute: typeof ApiPluginsYankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/versions': {
      id: '/api/plugins/versions'
      path: '/api/plugins/versions'
      fullPath: '/api/plugins/versions'
      preLoaderRoute: typeof ApiPluginsVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/deprecate': {
      id: '/api/plugins/deprecate'
      path: '/api/plugins/deprecate'
      fullPath: '/api/plugins/deprecate'
      preLoaderRoute: typeof ApiPluginsDeprecateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orgs/$org': {
      id: '/api/orgs/$org'
      path: '/$org'
      fullPath: '/api/orgs/$org'
      preLoaderRoute: typeof ApiOrgsOrgRouteImport
      parentRoute: typeof ApiOrgsRoute
    }
    '/api/device/approve': {
      id: '/api/device/approve'
      path: '/api/device/approve'
      fullPath: '/api/device/approve'
      preLoaderRoute: typeof ApiDeviceApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/tokens': {
      id: '/api/account/tokens'
      path: '/api/account/tokens'
      fullPath: '/api/account/tokens'
      preLoaderRoute: typeof ApiAccountTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/profile': {
      id: '/api/account/profile'
      path: '/api/account/profile'
      fullPath: '/api/account/profile'
      preLoaderRoute: typeof ApiAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/plugins/$name/versions': {
      id: '/v1/plugins/$name/versions'
      path: '/versions'
      fullPath: '/v1/plugins/$name/versions'
      preLoaderRoute: typeof V1PluginsNameVersionsRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/reviews': {
      id: '/v1/plugins/$name/reviews'
      path: '/reviews'
      fullPath: '/v1/plugins/$name/reviews'
      preLoaderRoute: typeof V1PluginsNameReviewsRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/readme': {
      id: '/v1/plugins/$name/readme'
      path: '/readme'
      fullPath: '/v1/plugins/$name/readme'
      preLoaderRoute: typeof V1PluginsNameReadmeRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/comments': {
      id: '/v1/plugins/$name/comments'
      path: '/comments'
      fullPath: '/v1/plugins/$name/comments'
      preLoaderRoute: typeof V1PluginsNameCommentsRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/api/plugins/$name/listing': {
      id: '/api/plugins/$name/listing'
      path: '/api/plugins/$name/listing'
      fullPath: '/api/plugins/$name/listing'
      preLoaderRoute: typeof ApiPluginsNameListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orgs/$org/scopes': {
      id: '/api/orgs/$org/scopes'
      path: '/scopes'
      fullPath: '/api/orgs/$org/scopes'
      preLoaderRoute: typeof ApiOrgsOrgScopesRouteImport
      parentRoute: typeof ApiOrgsOrgRoute
    }
    '/api/orgs/$org/profile': {
      id: '/api/orgs/$org/profile'
      path: '/profile'
      fullPath: '/api/orgs/$org/profile'
      preLoaderRoute: typeof ApiOrgsOrgProfileRouteImport
      parentRoute: typeof ApiOrgsOrgRoute
    }
    '/api/orgs/$org/members': {
      id: '/api/orgs/$org/members'
      path: '/members'
      fullPath: '/api/orgs/$org/members'
      preLoaderRoute: typeof ApiOrgsOrgMembersRouteImport
      parentRoute: typeof ApiOrgsOrgRoute
    }
    '/api/orgs/$org/icon': {
      id: '/api/orgs/$org/icon'
      path: '/icon'
      fullPath: '/api/orgs/$org/icon'
      preLoaderRoute: typeof ApiOrgsOrgIconRouteImport
      parentRoute: typeof ApiOrgsOrgRoute
    }
    '/api/orgs/$org/domains': {
      id: '/api/orgs/$org/domains'
      path: '/domains'
      fullPath: '/api/orgs/$org/domains'
      preLoaderRoute: typeof ApiOrgsOrgDomainsRouteImport
      parentRoute: typeof ApiOrgsOrgRoute
    }
    '/api/orgs/$org/display-name': {
      id: '/api/orgs/$org/display-name'
      path: '/display-name'
      fullPath: '/api/orgs/$org/display-name'
      preLoaderRoute: typeof ApiOrgsOrgDisplayNameRouteImport
      parentRoute: typeof ApiOrgsOrgRoute
    }
    '/api/account/tokens/$hash': {
      id: '/api/account/tokens/$hash'
      path: '/$hash'
      fullPath: '/api/account/tokens/$hash'
      preLoaderRoute: typeof ApiAccountTokensHashRouteImport
      parentRoute: typeof ApiAccountTokensRoute
    }
    '/api/orgs/$org/members/$memberId': {
      id: '/api/orgs/$org/members/$memberId'
      path: '/$memberId'
      fullPath: '/api/orgs/$org/members/$memberId'
      preLoaderRoute: typeof ApiOrgsOrgMembersMemberIdRouteImport
      parentRoute: typeof ApiOrgsOrgMembersRoute
    }
    '/v1/plugins/$name/v/$version/index': {
      id: '/v1/plugins/$name/v/$version/index'
      path: '/v/$version/index'
      fullPath: '/v1/plugins/$name/v/$version/index'
      preLoaderRoute: typeof V1PluginsNameVVersionChar91indexChar93RouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/reviews/$reviewId/vote': {
      id: '/v1/plugins/$name/reviews/$reviewId/vote'
      path: '/$reviewId/vote'
      fullPath: '/v1/plugins/$name/reviews/$reviewId/vote'
      preLoaderRoute: typeof V1PluginsNameReviewsReviewIdVoteRouteImport
      parentRoute: typeof V1PluginsNameReviewsRoute
    }
    '/v1/plugins/$name/comments/$commentId/vote': {
      id: '/v1/plugins/$name/comments/$commentId/vote'
      path: '/$commentId/vote'
      fullPath: '/v1/plugins/$name/comments/$commentId/vote'
      preLoaderRoute: typeof V1PluginsNameCommentsCommentIdVoteRouteImport
      parentRoute: typeof V1PluginsNameCommentsRoute
    }
    '/v1/plugins/$name/v/$version/files/$': {
      id: '/v1/plugins/$name/v/$version/files/$'
      path: '/v/$version/files/$'
      fullPath: '/v1/plugins/$name/v/$version/files/$'
      preLoaderRoute: typeof V1PluginsNameVVersionFilesSplatRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardOrgsRoute: typeof DashboardOrgsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountTokensRoute: typeof DashboardAccountTokensRoute
  DashboardOrgsOrgRoute: typeof DashboardOrgsOrgRoute
  DashboardPluginsSplatRoute: typeof DashboardPluginsSplatRoute
  DashboardPluginsIndexRoute: typeof DashboardPluginsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOrgsRoute: DashboardOrgsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountTokensRoute: DashboardAccountTokensRoute,
  DashboardOrgsOrgRoute: DashboardOrgsOrgRoute,
  DashboardPluginsSplatRoute: DashboardPluginsSplatRoute,
  DashboardPluginsIndexRoute: DashboardPluginsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiOrgsOrgMembersRouteChildren {
  ApiOrgsOrgMembersMemberIdRoute: typeof ApiOrgsOrgMembersMemberIdRoute
}

const ApiOrgsOrgMembersRouteChildren: ApiOrgsOrgMembersRouteChildren = {
  ApiOrgsOrgMembersMemberIdRoute: ApiOrgsOrgMembersMemberIdRoute,
}

const ApiOrgsOrgMembersRouteWithChildren =
  ApiOrgsOrgMembersRoute._addFileChildren(ApiOrgsOrgMembersRouteChildren)

interface ApiOrgsOrgRouteChildren {
  ApiOrgsOrgDisplayNameRoute: typeof ApiOrgsOrgDisplayNameRoute
  ApiOrgsOrgDomainsRoute: typeof ApiOrgsOrgDomainsRoute
  ApiOrgsOrgIconRoute: typeof ApiOrgsOrgIconRoute
  ApiOrgsOrgMembersRoute: typeof ApiOrgsOrgMembersRouteWithChildren
  ApiOrgsOrgProfileRoute: typeof ApiOrgsOrgProfileRoute
  ApiOrgsOrgScopesRoute: typeof ApiOrgsOrgScopesRoute
}

const ApiOrgsOrgRouteChildren: ApiOrgsOrgRouteChildren = {
  ApiOrgsOrgDisplayNameRoute: ApiOrgsOrgDisplayNameRoute,
  ApiOrgsOrgDomainsRoute: ApiOrgsOrgDomainsRoute,
  ApiOrgsOrgIconRoute: ApiOrgsOrgIconRoute,
  ApiOrgsOrgMembersRoute: ApiOrgsOrgMembersRouteWithChildren,
  ApiOrgsOrgProfileRoute: ApiOrgsOrgProfileRoute,
  ApiOrgsOrgScopesRoute: ApiOrgsOrgScopesRoute,
}

const ApiOrgsOrgRouteWithChildren = ApiOrgsOrgRoute._addFileChildren(
  ApiOrgsOrgRouteChildren,
)

interface ApiOrgsRouteChildren {
  ApiOrgsOrgRoute: typeof ApiOrgsOrgRouteWithChildren
}

const ApiOrgsRouteChildren: ApiOrgsRouteChildren = {
  ApiOrgsOrgRoute: ApiOrgsOrgRouteWithChildren,
}

const ApiOrgsRouteWithChildren =
  ApiOrgsRoute._addFileChildren(ApiOrgsRouteChildren)

interface AuthGithubRouteChildren {
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

const AuthGithubRouteChildren: AuthGithubRouteChildren = {
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}

const AuthGithubRouteWithChildren = AuthGithubRoute._addFileChildren(
  AuthGithubRouteChildren,
)

interface ApiAccountTokensRouteChildren {
  ApiAccountTokensHashRoute: typeof ApiAccountTokensHashRoute
}

const ApiAccountTokensRouteChildren: ApiAccountTokensRouteChildren = {
  ApiAccountTokensHashRoute: ApiAccountTokensHashRoute,
}

const ApiAccountTokensRouteWithChildren =
  ApiAccountTokensRoute._addFileChildren(ApiAccountTokensRouteChildren)

interface V1PluginsNameCommentsRouteChildren {
  V1PluginsNameCommentsCommentIdVoteRoute: typeof V1PluginsNameCommentsCommentIdVoteRoute
}

const V1PluginsNameCommentsRouteChildren: V1PluginsNameCommentsRouteChildren = {
  V1PluginsNameCommentsCommentIdVoteRoute:
    V1PluginsNameCommentsCommentIdVoteRoute,
}

const V1PluginsNameCommentsRouteWithChildren =
  V1PluginsNameCommentsRoute._addFileChildren(
    V1PluginsNameCommentsRouteChildren,
  )

interface V1PluginsNameReviewsRouteChildren {
  V1PluginsNameReviewsReviewIdVoteRoute: typeof V1PluginsNameReviewsReviewIdVoteRoute
}

const V1PluginsNameReviewsRouteChildren: V1PluginsNameReviewsRouteChildren = {
  V1PluginsNameReviewsReviewIdVoteRoute: V1PluginsNameReviewsReviewIdVoteRoute,
}

const V1PluginsNameReviewsRouteWithChildren =
  V1PluginsNameReviewsRoute._addFileChildren(V1PluginsNameReviewsRouteChildren)

interface V1PluginsNameRouteChildren {
  V1PluginsNameCommentsRoute: typeof V1PluginsNameCommentsRouteWithChildren
  V1PluginsNameReadmeRoute: typeof V1PluginsNameReadmeRoute
  V1PluginsNameReviewsRoute: typeof V1PluginsNameReviewsRouteWithChildren
  V1PluginsNameVersionsRoute: typeof V1PluginsNameVersionsRoute
  V1PluginsNameVVersionChar91indexChar93Route: typeof V1PluginsNameVVersionChar91indexChar93Route
  V1PluginsNameVVersionFilesSplatRoute: typeof V1PluginsNameVVersionFilesSplatRoute
}

const V1PluginsNameRouteChildren: V1PluginsNameRouteChildren = {
  V1PluginsNameCommentsRoute: V1PluginsNameCommentsRouteWithChildren,
  V1PluginsNameReadmeRoute: V1PluginsNameReadmeRoute,
  V1PluginsNameReviewsRoute: V1PluginsNameReviewsRouteWithChildren,
  V1PluginsNameVersionsRoute: V1PluginsNameVersionsRoute,
  V1PluginsNameVVersionChar91indexChar93Route:
    V1PluginsNameVVersionChar91indexChar93Route,
  V1PluginsNameVVersionFilesSplatRoute: V1PluginsNameVVersionFilesSplatRoute,
}

const V1PluginsNameRouteWithChildren = V1PluginsNameRoute._addFileChildren(
  V1PluginsNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeviceRoute: DeviceRoute,
  ApiOrgsRoute: ApiOrgsRouteWithChildren,
  AuthGithubRoute: AuthGithubRouteWithChildren,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthMeRoute: AuthMeRoute,
  DevelopersIdRoute: DevelopersIdRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalLicensesRoute: LegalLicensesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  OrgsOrgRoute: OrgsOrgRoute,
  PluginsSplatRoute: PluginsSplatRoute,
  V1RegistryRoute: V1RegistryRoute,
  V1SearchRoute: V1SearchRoute,
  V1VerifiedRoute: V1VerifiedRoute,
  LegalIndexRoute: LegalIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  ApiAccountProfileRoute: ApiAccountProfileRoute,
  ApiAccountTokensRoute: ApiAccountTokensRouteWithChildren,
  ApiDeviceApproveRoute: ApiDeviceApproveRoute,
  ApiPluginsDeprecateRoute: ApiPluginsDeprecateRoute,
  ApiPluginsVersionsRoute: ApiPluginsVersionsRoute,
  ApiPluginsYankRoute: ApiPluginsYankRoute,
  V1DevelopersIdRoute: V1DevelopersIdRoute,
  V1PluginsNameRoute: V1PluginsNameRouteWithChildren,
  ApiPluginsNameListingRoute: ApiPluginsNameListingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
