/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as OperatorIndexRouteImport } from './routes/operator/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as V1VerifiedRouteImport } from './routes/v1/verified'
import { Route as V1SearchRouteImport } from './routes/v1/search'
import { Route as V1RegistryRouteImport } from './routes/v1/registry'
import { Route as UIdRouteImport } from './routes/u/$id'
import { Route as OperatorScopesRouteImport } from './routes/operator/scopes'
import { Route as OperatorReportsRouteImport } from './routes/operator/reports'
import { Route as OperatorPluginsRouteImport } from './routes/operator/plugins'
import { Route as OperatorAuditRouteImport } from './routes/operator/audit'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalLicensesRouteImport } from './routes/legal/licenses'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal/acceptable-use'
import { Route as DashboardScopesRouteImport } from './routes/dashboard/scopes'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard/accounts'
import { Route as AuthMeRouteImport } from './routes/auth/me'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthGithubRouteImport } from './routes/auth/github'
import { Route as AssetsSplatRouteImport } from './routes/assets/$'
import { Route as ApiScopesRouteImport } from './routes/api/scopes'
import { Route as DashboardPluginsIndexRouteImport } from './routes/dashboard/plugins/index'
import { Route as V1PluginsNameRouteImport } from './routes/v1/plugins/$name'
import { Route as DashboardScopesScopeRouteImport } from './routes/dashboard/scopes_/$scope'
import { Route as DashboardPluginsCreateRouteImport } from './routes/dashboard/plugins/create'
import { Route as DashboardPluginsSplatRouteImport } from './routes/dashboard/plugins/$'
import { Route as DashboardAccountTokensRouteImport } from './routes/dashboard/account/tokens'
import { Route as ApiScopesScopeRouteImport } from './routes/api/scopes/$scope'
import { Route as ApiPluginsYankRouteImport } from './routes/api/plugins/yank'
import { Route as ApiPluginsVersionsRouteImport } from './routes/api/plugins/versions'
import { Route as ApiPluginsMineRouteImport } from './routes/api/plugins/mine'
import { Route as ApiPluginsDeprecateRouteImport } from './routes/api/plugins/deprecate'
import { Route as ApiPluginsDeleteRouteImport } from './routes/api/plugins/delete'
import { Route as ApiPluginsCreateRouteImport } from './routes/api/plugins/create'
import { Route as ApiOperatorScopesRouteImport } from './routes/api/operator/scopes'
import { Route as ApiOperatorReportsRouteImport } from './routes/api/operator/reports'
import { Route as ApiOperatorPluginsRouteImport } from './routes/api/operator/plugins'
import { Route as ApiOperatorAuditRouteImport } from './routes/api/operator/audit'
import { Route as ApiDeviceApproveRouteImport } from './routes/api/device/approve'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAccountTokensRouteImport } from './routes/api/account/tokens'
import { Route as ApiAccountProfileRouteImport } from './routes/api/account/profile'
import { Route as ApiAccountAvatarRouteImport } from './routes/api/account/avatar'
import { Route as ApiAccountActivityRouteImport } from './routes/api/account/activity'
import { Route as V1PluginsNameVersionsRouteImport } from './routes/v1/plugins/$name/versions'
import { Route as V1PluginsNameReviewsRouteImport } from './routes/v1/plugins/$name/reviews'
import { Route as V1PluginsNameReportsRouteImport } from './routes/v1/plugins/$name/reports'
import { Route as V1PluginsNameReadmeRouteImport } from './routes/v1/plugins/$name/readme'
import { Route as V1PluginsNameCommentsRouteImport } from './routes/v1/plugins/$name/comments'
import { Route as ApiScopesScopeTrustedPublishersRouteImport } from './routes/api/scopes/$scope/trusted-publishers'
import { Route as ApiScopesScopeProfileRouteImport } from './routes/api/scopes/$scope/profile'
import { Route as ApiScopesScopeMembersRouteImport } from './routes/api/scopes/$scope/members'
import { Route as ApiScopesScopeIconRouteImport } from './routes/api/scopes/$scope/icon'
import { Route as ApiScopesScopeDomainsRouteImport } from './routes/api/scopes/$scope/domains'
import { Route as ApiScopesScopeDisplayNameRouteImport } from './routes/api/scopes/$scope/display-name'
import { Route as ApiOperatorReportsUpdateRouteImport } from './routes/api/operator/reports/update'
import { Route as ApiOperatorPluginsVersionsRouteImport } from './routes/api/operator/plugins/versions'
import { Route as ApiOperatorPluginsVerifyRouteImport } from './routes/api/operator/plugins/verify'
import { Route as ApiOperatorPluginsTakedownRouteImport } from './routes/api/operator/plugins/takedown'
import { Route as ApiOperatorPluginsRestoreRouteImport } from './routes/api/operator/plugins/restore'
import { Route as ApiOperatorPluginsPluginRestoreRouteImport } from './routes/api/operator/plugins/plugin-restore'
import { Route as ApiOperatorPluginsBulkTakedownRouteImport } from './routes/api/operator/plugins/bulk-takedown'
import { Route as ApiAccountTokensHashRouteImport } from './routes/api/account/tokens/$hash'
import { Route as ApiScopesScopeMembersMemberIdRouteImport } from './routes/api/scopes/$scope/members/$memberId'
import { Route as ApiOperatorScopesScopeVerifyRouteImport } from './routes/api/operator/scopes/$scope/verify'
import { Route as ApiOperatorScopesScopeTakedownRouteImport } from './routes/api/operator/scopes/$scope/takedown'
import { Route as ApiOperatorScopesScopeRestoreRouteImport } from './routes/api/operator/scopes/$scope/restore'
import { Route as V1PluginsNameVVersionChar91indexChar93RouteImport } from './routes/v1/plugins/$name/v/$version/[index]'
import { Route as V1PluginsNameReviewsReviewIdVoteRouteImport } from './routes/v1/plugins/$name/reviews/$reviewId/vote'
import { Route as V1PluginsNameCommentsCommentIdVoteRouteImport } from './routes/v1/plugins/$name/comments/$commentId/vote'
import { Route as V1PluginsNameVVersionFilesSplatRouteImport } from './routes/v1/plugins/$name/v/$version/files/$'

const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const V1VerifiedRoute = V1VerifiedRouteImport.update({
  id: '/v1/verified',
  path: '/v1/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SearchRoute = V1SearchRouteImport.update({
  id: '/v1/search',
  path: '/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RegistryRoute = V1RegistryRouteImport.update({
  id: '/v1/registry',
  path: '/v1/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorScopesRoute = OperatorScopesRouteImport.update({
  id: '/scopes',
  path: '/scopes',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorReportsRoute = OperatorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPluginsRoute = OperatorPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAuditRoute = OperatorAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OperatorRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLicensesRoute = LegalLicensesRouteImport.update({
  id: '/legal/licenses',
  path: '/legal/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScopesRoute = DashboardScopesRouteImport.update({
  id: '/scopes',
  path: '/scopes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthMeRoute = AuthMeRouteImport.update({
  id: '/auth/me',
  path: '/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/auth/github',
  path: '/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScopesRoute = ApiScopesRouteImport.update({
  id: '/api/scopes',
  path: '/api/scopes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPluginsIndexRoute = DashboardPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => DashboardRoute,
} as any)
const V1PluginsNameRoute = V1PluginsNameRouteImport.update({
  id: '/v1/plugins/$name',
  path: '/v1/plugins/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScopesScopeRoute = DashboardScopesScopeRouteImport.update({
  id: '/scopes_/$scope',
  path: '/scopes/$scope',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPluginsCreateRoute = DashboardPluginsCreateRouteImport.update({
  id: '/plugins/create',
  path: '/plugins/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPluginsSplatRoute = DashboardPluginsSplatRouteImport.update({
  id: '/plugins/$',
  path: '/plugins/$',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountTokensRoute = DashboardAccountTokensRouteImport.update({
  id: '/account/tokens',
  path: '/account/tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiScopesScopeRoute = ApiScopesScopeRouteImport.update({
  id: '/$scope',
  path: '/$scope',
  getParentRoute: () => ApiScopesRoute,
} as any)
const ApiPluginsYankRoute = ApiPluginsYankRouteImport.update({
  id: '/api/plugins/yank',
  path: '/api/plugins/yank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsVersionsRoute = ApiPluginsVersionsRouteImport.update({
  id: '/api/plugins/versions',
  path: '/api/plugins/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsMineRoute = ApiPluginsMineRouteImport.update({
  id: '/api/plugins/mine',
  path: '/api/plugins/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsDeprecateRoute = ApiPluginsDeprecateRouteImport.update({
  id: '/api/plugins/deprecate',
  path: '/api/plugins/deprecate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsDeleteRoute = ApiPluginsDeleteRouteImport.update({
  id: '/api/plugins/delete',
  path: '/api/plugins/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsCreateRoute = ApiPluginsCreateRouteImport.update({
  id: '/api/plugins/create',
  path: '/api/plugins/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorScopesRoute = ApiOperatorScopesRouteImport.update({
  id: '/api/operator/scopes',
  path: '/api/operator/scopes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorReportsRoute = ApiOperatorReportsRouteImport.update({
  id: '/api/operator/reports',
  path: '/api/operator/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorPluginsRoute = ApiOperatorPluginsRouteImport.update({
  id: '/api/operator/plugins',
  path: '/api/operator/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorAuditRoute = ApiOperatorAuditRouteImport.update({
  id: '/api/operator/audit',
  path: '/api/operator/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceApproveRoute = ApiDeviceApproveRouteImport.update({
  id: '/api/device/approve',
  path: '/api/device/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountTokensRoute = ApiAccountTokensRouteImport.update({
  id: '/api/account/tokens',
  path: '/api/account/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountProfileRoute = ApiAccountProfileRouteImport.update({
  id: '/api/account/profile',
  path: '/api/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountAvatarRoute = ApiAccountAvatarRouteImport.update({
  id: '/api/account/avatar',
  path: '/api/account/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountActivityRoute = ApiAccountActivityRouteImport.update({
  id: '/api/account/activity',
  path: '/api/account/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const V1PluginsNameVersionsRoute = V1PluginsNameVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const V1PluginsNameReviewsRoute = V1PluginsNameReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const V1PluginsNameReportsRoute = V1PluginsNameReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const V1PluginsNameReadmeRoute = V1PluginsNameReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const V1PluginsNameCommentsRoute = V1PluginsNameCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => V1PluginsNameRoute,
} as any)
const ApiScopesScopeTrustedPublishersRoute =
  ApiScopesScopeTrustedPublishersRouteImport.update({
    id: '/trusted-publishers',
    path: '/trusted-publishers',
    getParentRoute: () => ApiScopesScopeRoute,
  } as any)
const ApiScopesScopeProfileRoute = ApiScopesScopeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ApiScopesScopeRoute,
} as any)
const ApiScopesScopeMembersRoute = ApiScopesScopeMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiScopesScopeRoute,
} as any)
const ApiScopesScopeIconRoute = ApiScopesScopeIconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => ApiScopesScopeRoute,
} as any)
const ApiScopesScopeDomainsRoute = ApiScopesScopeDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ApiScopesScopeRoute,
} as any)
const ApiScopesScopeDisplayNameRoute =
  ApiScopesScopeDisplayNameRouteImport.update({
    id: '/display-name',
    path: '/display-name',
    getParentRoute: () => ApiScopesScopeRoute,
  } as any)
const ApiOperatorReportsUpdateRoute =
  ApiOperatorReportsUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => ApiOperatorReportsRoute,
  } as any)
const ApiOperatorPluginsVersionsRoute =
  ApiOperatorPluginsVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ApiOperatorPluginsRoute,
  } as any)
const ApiOperatorPluginsVerifyRoute =
  ApiOperatorPluginsVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiOperatorPluginsRoute,
  } as any)
const ApiOperatorPluginsTakedownRoute =
  ApiOperatorPluginsTakedownRouteImport.update({
    id: '/takedown',
    path: '/takedown',
    getParentRoute: () => ApiOperatorPluginsRoute,
  } as any)
const ApiOperatorPluginsRestoreRoute =
  ApiOperatorPluginsRestoreRouteImport.update({
    id: '/restore',
    path: '/restore',
    getParentRoute: () => ApiOperatorPluginsRoute,
  } as any)
const ApiOperatorPluginsPluginRestoreRoute =
  ApiOperatorPluginsPluginRestoreRouteImport.update({
    id: '/plugin-restore',
    path: '/plugin-restore',
    getParentRoute: () => ApiOperatorPluginsRoute,
  } as any)
const ApiOperatorPluginsBulkTakedownRoute =
  ApiOperatorPluginsBulkTakedownRouteImport.update({
    id: '/bulk-takedown',
    path: '/bulk-takedown',
    getParentRoute: () => ApiOperatorPluginsRoute,
  } as any)
const ApiAccountTokensHashRoute = ApiAccountTokensHashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => ApiAccountTokensRoute,
} as any)
const ApiScopesScopeMembersMemberIdRoute =
  ApiScopesScopeMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => ApiScopesScopeMembersRoute,
  } as any)
const ApiOperatorScopesScopeVerifyRoute =
  ApiOperatorScopesScopeVerifyRouteImport.update({
    id: '/$scope/verify',
    path: '/$scope/verify',
    getParentRoute: () => ApiOperatorScopesRoute,
  } as any)
const ApiOperatorScopesScopeTakedownRoute =
  ApiOperatorScopesScopeTakedownRouteImport.update({
    id: '/$scope/takedown',
    path: '/$scope/takedown',
    getParentRoute: () => ApiOperatorScopesRoute,
  } as any)
const ApiOperatorScopesScopeRestoreRoute =
  ApiOperatorScopesScopeRestoreRouteImport.update({
    id: '/$scope/restore',
    path: '/$scope/restore',
    getParentRoute: () => ApiOperatorScopesRoute,
  } as any)
const V1PluginsNameVVersionChar91indexChar93Route =
  V1PluginsNameVVersionChar91indexChar93RouteImport.update({
    id: '/v/$version/index',
    path: '/v/$version/index',
    getParentRoute: () => V1PluginsNameRoute,
  } as any)
const V1PluginsNameReviewsReviewIdVoteRoute =
  V1PluginsNameReviewsReviewIdVoteRouteImport.update({
    id: '/$reviewId/vote',
    path: '/$reviewId/vote',
    getParentRoute: () => V1PluginsNameReviewsRoute,
  } as any)
const V1PluginsNameCommentsCommentIdVoteRoute =
  V1PluginsNameCommentsCommentIdVoteRouteImport.update({
    id: '/$commentId/vote',
    path: '/$commentId/vote',
    getParentRoute: () => V1PluginsNameCommentsRoute,
  } as any)
const V1PluginsNameVVersionFilesSplatRoute =
  V1PluginsNameVVersionFilesSplatRouteImport.update({
    id: '/v/$version/files/$',
    path: '/v/$version/files/$',
    getParentRoute: () => V1PluginsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/api/scopes': typeof ApiScopesRouteWithChildren
  '/assets/$': typeof AssetsSplatRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scopes': typeof DashboardScopesRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/licenses': typeof LegalLicensesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/operator/audit': typeof OperatorAuditRoute
  '/operator/plugins': typeof OperatorPluginsRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/scopes': typeof OperatorScopesRoute
  '/u/$id': typeof UIdRoute
  '/v1/registry': typeof V1RegistryRoute
  '/v1/search': typeof V1SearchRoute
  '/v1/verified': typeof V1VerifiedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/api/account/activity': typeof ApiAccountActivityRoute
  '/api/account/avatar': typeof ApiAccountAvatarRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tokens': typeof ApiAccountTokensRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/device/approve': typeof ApiDeviceApproveRoute
  '/api/operator/audit': typeof ApiOperatorAuditRoute
  '/api/operator/plugins': typeof ApiOperatorPluginsRouteWithChildren
  '/api/operator/reports': typeof ApiOperatorReportsRouteWithChildren
  '/api/operator/scopes': typeof ApiOperatorScopesRouteWithChildren
  '/api/plugins/create': typeof ApiPluginsCreateRoute
  '/api/plugins/delete': typeof ApiPluginsDeleteRoute
  '/api/plugins/deprecate': typeof ApiPluginsDeprecateRoute
  '/api/plugins/mine': typeof ApiPluginsMineRoute
  '/api/plugins/versions': typeof ApiPluginsVersionsRoute
  '/api/plugins/yank': typeof ApiPluginsYankRoute
  '/api/scopes/$scope': typeof ApiScopesScopeRouteWithChildren
  '/dashboard/account/tokens': typeof DashboardAccountTokensRoute
  '/dashboard/plugins/$': typeof DashboardPluginsSplatRoute
  '/dashboard/plugins/create': typeof DashboardPluginsCreateRoute
  '/dashboard/scopes/$scope': typeof DashboardScopesScopeRoute
  '/v1/plugins/$name': typeof V1PluginsNameRouteWithChildren
  '/dashboard/plugins/': typeof DashboardPluginsIndexRoute
  '/api/account/tokens/$hash': typeof ApiAccountTokensHashRoute
  '/api/operator/plugins/bulk-takedown': typeof ApiOperatorPluginsBulkTakedownRoute
  '/api/operator/plugins/plugin-restore': typeof ApiOperatorPluginsPluginRestoreRoute
  '/api/operator/plugins/restore': typeof ApiOperatorPluginsRestoreRoute
  '/api/operator/plugins/takedown': typeof ApiOperatorPluginsTakedownRoute
  '/api/operator/plugins/verify': typeof ApiOperatorPluginsVerifyRoute
  '/api/operator/plugins/versions': typeof ApiOperatorPluginsVersionsRoute
  '/api/operator/reports/update': typeof ApiOperatorReportsUpdateRoute
  '/api/scopes/$scope/display-name': typeof ApiScopesScopeDisplayNameRoute
  '/api/scopes/$scope/domains': typeof ApiScopesScopeDomainsRoute
  '/api/scopes/$scope/icon': typeof ApiScopesScopeIconRoute
  '/api/scopes/$scope/members': typeof ApiScopesScopeMembersRouteWithChildren
  '/api/scopes/$scope/profile': typeof ApiScopesScopeProfileRoute
  '/api/scopes/$scope/trusted-publishers': typeof ApiScopesScopeTrustedPublishersRoute
  '/v1/plugins/$name/comments': typeof V1PluginsNameCommentsRouteWithChildren
  '/v1/plugins/$name/readme': typeof V1PluginsNameReadmeRoute
  '/v1/plugins/$name/reports': typeof V1PluginsNameReportsRoute
  '/v1/plugins/$name/reviews': typeof V1PluginsNameReviewsRouteWithChildren
  '/v1/plugins/$name/versions': typeof V1PluginsNameVersionsRoute
  '/api/operator/scopes/$scope/restore': typeof ApiOperatorScopesScopeRestoreRoute
  '/api/operator/scopes/$scope/takedown': typeof ApiOperatorScopesScopeTakedownRoute
  '/api/operator/scopes/$scope/verify': typeof ApiOperatorScopesScopeVerifyRoute
  '/api/scopes/$scope/members/$memberId': typeof ApiScopesScopeMembersMemberIdRoute
  '/v1/plugins/$name/comments/$commentId/vote': typeof V1PluginsNameCommentsCommentIdVoteRoute
  '/v1/plugins/$name/reviews/$reviewId/vote': typeof V1PluginsNameReviewsReviewIdVoteRoute
  '/v1/plugins/$name/v/$version/index': typeof V1PluginsNameVVersionChar91indexChar93Route
  '/v1/plugins/$name/v/$version/files/$': typeof V1PluginsNameVVersionFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/api/scopes': typeof ApiScopesRouteWithChildren
  '/assets/$': typeof AssetsSplatRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scopes': typeof DashboardScopesRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/licenses': typeof LegalLicensesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/operator/audit': typeof OperatorAuditRoute
  '/operator/plugins': typeof OperatorPluginsRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/scopes': typeof OperatorScopesRoute
  '/u/$id': typeof UIdRoute
  '/v1/registry': typeof V1RegistryRoute
  '/v1/search': typeof V1SearchRoute
  '/v1/verified': typeof V1VerifiedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/legal': typeof LegalIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/api/account/activity': typeof ApiAccountActivityRoute
  '/api/account/avatar': typeof ApiAccountAvatarRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tokens': typeof ApiAccountTokensRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/device/approve': typeof ApiDeviceApproveRoute
  '/api/operator/audit': typeof ApiOperatorAuditRoute
  '/api/operator/plugins': typeof ApiOperatorPluginsRouteWithChildren
  '/api/operator/reports': typeof ApiOperatorReportsRouteWithChildren
  '/api/operator/scopes': typeof ApiOperatorScopesRouteWithChildren
  '/api/plugins/create': typeof ApiPluginsCreateRoute
  '/api/plugins/delete': typeof ApiPluginsDeleteRoute
  '/api/plugins/deprecate': typeof ApiPluginsDeprecateRoute
  '/api/plugins/mine': typeof ApiPluginsMineRoute
  '/api/plugins/versions': typeof ApiPluginsVersionsRoute
  '/api/plugins/yank': typeof ApiPluginsYankRoute
  '/api/scopes/$scope': typeof ApiScopesScopeRouteWithChildren
  '/dashboard/account/tokens': typeof DashboardAccountTokensRoute
  '/dashboard/plugins/$': typeof DashboardPluginsSplatRoute
  '/dashboard/plugins/create': typeof DashboardPluginsCreateRoute
  '/dashboard/scopes/$scope': typeof DashboardScopesScopeRoute
  '/v1/plugins/$name': typeof V1PluginsNameRouteWithChildren
  '/dashboard/plugins': typeof DashboardPluginsIndexRoute
  '/api/account/tokens/$hash': typeof ApiAccountTokensHashRoute
  '/api/operator/plugins/bulk-takedown': typeof ApiOperatorPluginsBulkTakedownRoute
  '/api/operator/plugins/plugin-restore': typeof ApiOperatorPluginsPluginRestoreRoute
  '/api/operator/plugins/restore': typeof ApiOperatorPluginsRestoreRoute
  '/api/operator/plugins/takedown': typeof ApiOperatorPluginsTakedownRoute
  '/api/operator/plugins/verify': typeof ApiOperatorPluginsVerifyRoute
  '/api/operator/plugins/versions': typeof ApiOperatorPluginsVersionsRoute
  '/api/operator/reports/update': typeof ApiOperatorReportsUpdateRoute
  '/api/scopes/$scope/display-name': typeof ApiScopesScopeDisplayNameRoute
  '/api/scopes/$scope/domains': typeof ApiScopesScopeDomainsRoute
  '/api/scopes/$scope/icon': typeof ApiScopesScopeIconRoute
  '/api/scopes/$scope/members': typeof ApiScopesScopeMembersRouteWithChildren
  '/api/scopes/$scope/profile': typeof ApiScopesScopeProfileRoute
  '/api/scopes/$scope/trusted-publishers': typeof ApiScopesScopeTrustedPublishersRoute
  '/v1/plugins/$name/comments': typeof V1PluginsNameCommentsRouteWithChildren
  '/v1/plugins/$name/readme': typeof V1PluginsNameReadmeRoute
  '/v1/plugins/$name/reports': typeof V1PluginsNameReportsRoute
  '/v1/plugins/$name/reviews': typeof V1PluginsNameReviewsRouteWithChildren
  '/v1/plugins/$name/versions': typeof V1PluginsNameVersionsRoute
  '/api/operator/scopes/$scope/restore': typeof ApiOperatorScopesScopeRestoreRoute
  '/api/operator/scopes/$scope/takedown': typeof ApiOperatorScopesScopeTakedownRoute
  '/api/operator/scopes/$scope/verify': typeof ApiOperatorScopesScopeVerifyRoute
  '/api/scopes/$scope/members/$memberId': typeof ApiScopesScopeMembersMemberIdRoute
  '/v1/plugins/$name/comments/$commentId/vote': typeof V1PluginsNameCommentsCommentIdVoteRoute
  '/v1/plugins/$name/reviews/$reviewId/vote': typeof V1PluginsNameReviewsReviewIdVoteRoute
  '/v1/plugins/$name/v/$version/index': typeof V1PluginsNameVVersionChar91indexChar93Route
  '/v1/plugins/$name/v/$version/files/$': typeof V1PluginsNameVVersionFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/api/scopes': typeof ApiScopesRouteWithChildren
  '/assets/$': typeof AssetsSplatRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scopes': typeof DashboardScopesRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/licenses': typeof LegalLicensesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/operator/audit': typeof OperatorAuditRoute
  '/operator/plugins': typeof OperatorPluginsRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/scopes': typeof OperatorScopesRoute
  '/u/$id': typeof UIdRoute
  '/v1/registry': typeof V1RegistryRoute
  '/v1/search': typeof V1SearchRoute
  '/v1/verified': typeof V1VerifiedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/api/account/activity': typeof ApiAccountActivityRoute
  '/api/account/avatar': typeof ApiAccountAvatarRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tokens': typeof ApiAccountTokensRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/device/approve': typeof ApiDeviceApproveRoute
  '/api/operator/audit': typeof ApiOperatorAuditRoute
  '/api/operator/plugins': typeof ApiOperatorPluginsRouteWithChildren
  '/api/operator/reports': typeof ApiOperatorReportsRouteWithChildren
  '/api/operator/scopes': typeof ApiOperatorScopesRouteWithChildren
  '/api/plugins/create': typeof ApiPluginsCreateRoute
  '/api/plugins/delete': typeof ApiPluginsDeleteRoute
  '/api/plugins/deprecate': typeof ApiPluginsDeprecateRoute
  '/api/plugins/mine': typeof ApiPluginsMineRoute
  '/api/plugins/versions': typeof ApiPluginsVersionsRoute
  '/api/plugins/yank': typeof ApiPluginsYankRoute
  '/api/scopes/$scope': typeof ApiScopesScopeRouteWithChildren
  '/dashboard/account/tokens': typeof DashboardAccountTokensRoute
  '/dashboard/plugins/$': typeof DashboardPluginsSplatRoute
  '/dashboard/plugins/create': typeof DashboardPluginsCreateRoute
  '/dashboard/scopes_/$scope': typeof DashboardScopesScopeRoute
  '/v1/plugins/$name': typeof V1PluginsNameRouteWithChildren
  '/dashboard/plugins/': typeof DashboardPluginsIndexRoute
  '/api/account/tokens/$hash': typeof ApiAccountTokensHashRoute
  '/api/operator/plugins/bulk-takedown': typeof ApiOperatorPluginsBulkTakedownRoute
  '/api/operator/plugins/plugin-restore': typeof ApiOperatorPluginsPluginRestoreRoute
  '/api/operator/plugins/restore': typeof ApiOperatorPluginsRestoreRoute
  '/api/operator/plugins/takedown': typeof ApiOperatorPluginsTakedownRoute
  '/api/operator/plugins/verify': typeof ApiOperatorPluginsVerifyRoute
  '/api/operator/plugins/versions': typeof ApiOperatorPluginsVersionsRoute
  '/api/operator/reports/update': typeof ApiOperatorReportsUpdateRoute
  '/api/scopes/$scope/display-name': typeof ApiScopesScopeDisplayNameRoute
  '/api/scopes/$scope/domains': typeof ApiScopesScopeDomainsRoute
  '/api/scopes/$scope/icon': typeof ApiScopesScopeIconRoute
  '/api/scopes/$scope/members': typeof ApiScopesScopeMembersRouteWithChildren
  '/api/scopes/$scope/profile': typeof ApiScopesScopeProfileRoute
  '/api/scopes/$scope/trusted-publishers': typeof ApiScopesScopeTrustedPublishersRoute
  '/v1/plugins/$name/comments': typeof V1PluginsNameCommentsRouteWithChildren
  '/v1/plugins/$name/readme': typeof V1PluginsNameReadmeRoute
  '/v1/plugins/$name/reports': typeof V1PluginsNameReportsRoute
  '/v1/plugins/$name/reviews': typeof V1PluginsNameReviewsRouteWithChildren
  '/v1/plugins/$name/versions': typeof V1PluginsNameVersionsRoute
  '/api/operator/scopes/$scope/restore': typeof ApiOperatorScopesScopeRestoreRoute
  '/api/operator/scopes/$scope/takedown': typeof ApiOperatorScopesScopeTakedownRoute
  '/api/operator/scopes/$scope/verify': typeof ApiOperatorScopesScopeVerifyRoute
  '/api/scopes/$scope/members/$memberId': typeof ApiScopesScopeMembersMemberIdRoute
  '/v1/plugins/$name/comments/$commentId/vote': typeof V1PluginsNameCommentsCommentIdVoteRoute
  '/v1/plugins/$name/reviews/$reviewId/vote': typeof V1PluginsNameReviewsReviewIdVoteRoute
  '/v1/plugins/$name/v/$version/index': typeof V1PluginsNameVVersionChar91indexChar93Route
  '/v1/plugins/$name/v/$version/files/$': typeof V1PluginsNameVVersionFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/device'
    | '/login'
    | '/operator'
    | '/api/scopes'
    | '/assets/$'
    | '/auth/github'
    | '/auth/logout'
    | '/auth/me'
    | '/dashboard/accounts'
    | '/dashboard/profile'
    | '/dashboard/scopes'
    | '/legal/acceptable-use'
    | '/legal/cookies'
    | '/legal/licenses'
    | '/legal/privacy'
    | '/legal/terms'
    | '/operator/audit'
    | '/operator/plugins'
    | '/operator/reports'
    | '/operator/scopes'
    | '/u/$id'
    | '/v1/registry'
    | '/v1/search'
    | '/v1/verified'
    | '/dashboard/'
    | '/legal/'
    | '/operator/'
    | '/plugins/'
    | '/api/account/activity'
    | '/api/account/avatar'
    | '/api/account/profile'
    | '/api/account/tokens'
    | '/api/auth/$'
    | '/api/device/approve'
    | '/api/operator/audit'
    | '/api/operator/plugins'
    | '/api/operator/reports'
    | '/api/operator/scopes'
    | '/api/plugins/create'
    | '/api/plugins/delete'
    | '/api/plugins/deprecate'
    | '/api/plugins/mine'
    | '/api/plugins/versions'
    | '/api/plugins/yank'
    | '/api/scopes/$scope'
    | '/dashboard/account/tokens'
    | '/dashboard/plugins/$'
    | '/dashboard/plugins/create'
    | '/dashboard/scopes/$scope'
    | '/v1/plugins/$name'
    | '/dashboard/plugins/'
    | '/api/account/tokens/$hash'
    | '/api/operator/plugins/bulk-takedown'
    | '/api/operator/plugins/plugin-restore'
    | '/api/operator/plugins/restore'
    | '/api/operator/plugins/takedown'
    | '/api/operator/plugins/verify'
    | '/api/operator/plugins/versions'
    | '/api/operator/reports/update'
    | '/api/scopes/$scope/display-name'
    | '/api/scopes/$scope/domains'
    | '/api/scopes/$scope/icon'
    | '/api/scopes/$scope/members'
    | '/api/scopes/$scope/profile'
    | '/api/scopes/$scope/trusted-publishers'
    | '/v1/plugins/$name/comments'
    | '/v1/plugins/$name/readme'
    | '/v1/plugins/$name/reports'
    | '/v1/plugins/$name/reviews'
    | '/v1/plugins/$name/versions'
    | '/api/operator/scopes/$scope/restore'
    | '/api/operator/scopes/$scope/takedown'
    | '/api/operator/scopes/$scope/verify'
    | '/api/scopes/$scope/members/$memberId'
    | '/v1/plugins/$name/comments/$commentId/vote'
    | '/v1/plugins/$name/reviews/$reviewId/vote'
    | '/v1/plugins/$name/v/$version/index'
    | '/v1/plugins/$name/v/$version/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/device'
    | '/login'
    | '/api/scopes'
    | '/assets/$'
    | '/auth/github'
    | '/auth/logout'
    | '/auth/me'
    | '/dashboard/accounts'
    | '/dashboard/profile'
    | '/dashboard/scopes'
    | '/legal/acceptable-use'
    | '/legal/cookies'
    | '/legal/licenses'
    | '/legal/privacy'
    | '/legal/terms'
    | '/operator/audit'
    | '/operator/plugins'
    | '/operator/reports'
    | '/operator/scopes'
    | '/u/$id'
    | '/v1/registry'
    | '/v1/search'
    | '/v1/verified'
    | '/dashboard'
    | '/legal'
    | '/operator'
    | '/plugins'
    | '/api/account/activity'
    | '/api/account/avatar'
    | '/api/account/profile'
    | '/api/account/tokens'
    | '/api/auth/$'
    | '/api/device/approve'
    | '/api/operator/audit'
    | '/api/operator/plugins'
    | '/api/operator/reports'
    | '/api/operator/scopes'
    | '/api/plugins/create'
    | '/api/plugins/delete'
    | '/api/plugins/deprecate'
    | '/api/plugins/mine'
    | '/api/plugins/versions'
    | '/api/plugins/yank'
    | '/api/scopes/$scope'
    | '/dashboard/account/tokens'
    | '/dashboard/plugins/$'
    | '/dashboard/plugins/create'
    | '/dashboard/scopes/$scope'
    | '/v1/plugins/$name'
    | '/dashboard/plugins'
    | '/api/account/tokens/$hash'
    | '/api/operator/plugins/bulk-takedown'
    | '/api/operator/plugins/plugin-restore'
    | '/api/operator/plugins/restore'
    | '/api/operator/plugins/takedown'
    | '/api/operator/plugins/verify'
    | '/api/operator/plugins/versions'
    | '/api/operator/reports/update'
    | '/api/scopes/$scope/display-name'
    | '/api/scopes/$scope/domains'
    | '/api/scopes/$scope/icon'
    | '/api/scopes/$scope/members'
    | '/api/scopes/$scope/profile'
    | '/api/scopes/$scope/trusted-publishers'
    | '/v1/plugins/$name/comments'
    | '/v1/plugins/$name/readme'
    | '/v1/plugins/$name/reports'
    | '/v1/plugins/$name/reviews'
    | '/v1/plugins/$name/versions'
    | '/api/operator/scopes/$scope/restore'
    | '/api/operator/scopes/$scope/takedown'
    | '/api/operator/scopes/$scope/verify'
    | '/api/scopes/$scope/members/$memberId'
    | '/v1/plugins/$name/comments/$commentId/vote'
    | '/v1/plugins/$name/reviews/$reviewId/vote'
    | '/v1/plugins/$name/v/$version/index'
    | '/v1/plugins/$name/v/$version/files/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/device'
    | '/login'
    | '/operator'
    | '/api/scopes'
    | '/assets/$'
    | '/auth/github'
    | '/auth/logout'
    | '/auth/me'
    | '/dashboard/accounts'
    | '/dashboard/profile'
    | '/dashboard/scopes'
    | '/legal/acceptable-use'
    | '/legal/cookies'
    | '/legal/licenses'
    | '/legal/privacy'
    | '/legal/terms'
    | '/operator/audit'
    | '/operator/plugins'
    | '/operator/reports'
    | '/operator/scopes'
    | '/u/$id'
    | '/v1/registry'
    | '/v1/search'
    | '/v1/verified'
    | '/dashboard/'
    | '/legal/'
    | '/operator/'
    | '/plugins/'
    | '/api/account/activity'
    | '/api/account/avatar'
    | '/api/account/profile'
    | '/api/account/tokens'
    | '/api/auth/$'
    | '/api/device/approve'
    | '/api/operator/audit'
    | '/api/operator/plugins'
    | '/api/operator/reports'
    | '/api/operator/scopes'
    | '/api/plugins/create'
    | '/api/plugins/delete'
    | '/api/plugins/deprecate'
    | '/api/plugins/mine'
    | '/api/plugins/versions'
    | '/api/plugins/yank'
    | '/api/scopes/$scope'
    | '/dashboard/account/tokens'
    | '/dashboard/plugins/$'
    | '/dashboard/plugins/create'
    | '/dashboard/scopes_/$scope'
    | '/v1/plugins/$name'
    | '/dashboard/plugins/'
    | '/api/account/tokens/$hash'
    | '/api/operator/plugins/bulk-takedown'
    | '/api/operator/plugins/plugin-restore'
    | '/api/operator/plugins/restore'
    | '/api/operator/plugins/takedown'
    | '/api/operator/plugins/verify'
    | '/api/operator/plugins/versions'
    | '/api/operator/reports/update'
    | '/api/scopes/$scope/display-name'
    | '/api/scopes/$scope/domains'
    | '/api/scopes/$scope/icon'
    | '/api/scopes/$scope/members'
    | '/api/scopes/$scope/profile'
    | '/api/scopes/$scope/trusted-publishers'
    | '/v1/plugins/$name/comments'
    | '/v1/plugins/$name/readme'
    | '/v1/plugins/$name/reports'
    | '/v1/plugins/$name/reviews'
    | '/v1/plugins/$name/versions'
    | '/api/operator/scopes/$scope/restore'
    | '/api/operator/scopes/$scope/takedown'
    | '/api/operator/scopes/$scope/verify'
    | '/api/scopes/$scope/members/$memberId'
    | '/v1/plugins/$name/comments/$commentId/vote'
    | '/v1/plugins/$name/reviews/$reviewId/vote'
    | '/v1/plugins/$name/v/$version/index'
    | '/v1/plugins/$name/v/$version/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  ApiScopesRoute: typeof ApiScopesRouteWithChildren
  AssetsSplatRoute: typeof AssetsSplatRoute
  AuthGithubRoute: typeof AuthGithubRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthMeRoute: typeof AuthMeRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalLicensesRoute: typeof LegalLicensesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  UIdRoute: typeof UIdRoute
  V1RegistryRoute: typeof V1RegistryRoute
  V1SearchRoute: typeof V1SearchRoute
  V1VerifiedRoute: typeof V1VerifiedRoute
  LegalIndexRoute: typeof LegalIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  ApiAccountActivityRoute: typeof ApiAccountActivityRoute
  ApiAccountAvatarRoute: typeof ApiAccountAvatarRoute
  ApiAccountProfileRoute: typeof ApiAccountProfileRoute
  ApiAccountTokensRoute: typeof ApiAccountTokensRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDeviceApproveRoute: typeof ApiDeviceApproveRoute
  ApiOperatorAuditRoute: typeof ApiOperatorAuditRoute
  ApiOperatorPluginsRoute: typeof ApiOperatorPluginsRouteWithChildren
  ApiOperatorReportsRoute: typeof ApiOperatorReportsRouteWithChildren
  ApiOperatorScopesRoute: typeof ApiOperatorScopesRouteWithChildren
  ApiPluginsCreateRoute: typeof ApiPluginsCreateRoute
  ApiPluginsDeleteRoute: typeof ApiPluginsDeleteRoute
  ApiPluginsDeprecateRoute: typeof ApiPluginsDeprecateRoute
  ApiPluginsMineRoute: typeof ApiPluginsMineRoute
  ApiPluginsVersionsRoute: typeof ApiPluginsVersionsRoute
  ApiPluginsYankRoute: typeof ApiPluginsYankRoute
  V1PluginsNameRoute: typeof V1PluginsNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/v1/verified': {
      id: '/v1/verified'
      path: '/v1/verified'
      fullPath: '/v1/verified'
      preLoaderRoute: typeof V1VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/search': {
      id: '/v1/search'
      path: '/v1/search'
      fullPath: '/v1/search'
      preLoaderRoute: typeof V1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/registry': {
      id: '/v1/registry'
      path: '/v1/registry'
      fullPath: '/v1/registry'
      preLoaderRoute: typeof V1RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/scopes': {
      id: '/operator/scopes'
      path: '/scopes'
      fullPath: '/operator/scopes'
      preLoaderRoute: typeof OperatorScopesRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/reports': {
      id: '/operator/reports'
      path: '/reports'
      fullPath: '/operator/reports'
      preLoaderRoute: typeof OperatorReportsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/plugins': {
      id: '/operator/plugins'
      path: '/plugins'
      fullPath: '/operator/plugins'
      preLoaderRoute: typeof OperatorPluginsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/audit': {
      id: '/operator/audit'
      path: '/audit'
      fullPath: '/operator/audit'
      preLoaderRoute: typeof OperatorAuditRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/licenses': {
      id: '/legal/licenses'
      path: '/legal/licenses'
      fullPath: '/legal/licenses'
      preLoaderRoute: typeof LegalLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scopes': {
      id: '/dashboard/scopes'
      path: '/scopes'
      fullPath: '/dashboard/scopes'
      preLoaderRoute: typeof DashboardScopesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/me': {
      id: '/auth/me'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/auth/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scopes': {
      id: '/api/scopes'
      path: '/api/scopes'
      fullPath: '/api/scopes'
      preLoaderRoute: typeof ApiScopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/plugins/': {
      id: '/dashboard/plugins/'
      path: '/plugins'
      fullPath: '/dashboard/plugins/'
      preLoaderRoute: typeof DashboardPluginsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/v1/plugins/$name': {
      id: '/v1/plugins/$name'
      path: '/v1/plugins/$name'
      fullPath: '/v1/plugins/$name'
      preLoaderRoute: typeof V1PluginsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scopes_/$scope': {
      id: '/dashboard/scopes_/$scope'
      path: '/scopes/$scope'
      fullPath: '/dashboard/scopes/$scope'
      preLoaderRoute: typeof DashboardScopesScopeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plugins/create': {
      id: '/dashboard/plugins/create'
      path: '/plugins/create'
      fullPath: '/dashboard/plugins/create'
      preLoaderRoute: typeof DashboardPluginsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plugins/$': {
      id: '/dashboard/plugins/$'
      path: '/plugins/$'
      fullPath: '/dashboard/plugins/$'
      preLoaderRoute: typeof DashboardPluginsSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account/tokens': {
      id: '/dashboard/account/tokens'
      path: '/account/tokens'
      fullPath: '/dashboard/account/tokens'
      preLoaderRoute: typeof DashboardAccountTokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/scopes/$scope': {
      id: '/api/scopes/$scope'
      path: '/$scope'
      fullPath: '/api/scopes/$scope'
      preLoaderRoute: typeof ApiScopesScopeRouteImport
      parentRoute: typeof ApiScopesRoute
    }
    '/api/plugins/yank': {
      id: '/api/plugins/yank'
      path: '/api/plugins/yank'
      fullPath: '/api/plugins/yank'
      preLoaderRoute: typeof ApiPluginsYankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/versions': {
      id: '/api/plugins/versions'
      path: '/api/plugins/versions'
      fullPath: '/api/plugins/versions'
      preLoaderRoute: typeof ApiPluginsVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/mine': {
      id: '/api/plugins/mine'
      path: '/api/plugins/mine'
      fullPath: '/api/plugins/mine'
      preLoaderRoute: typeof ApiPluginsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/deprecate': {
      id: '/api/plugins/deprecate'
      path: '/api/plugins/deprecate'
      fullPath: '/api/plugins/deprecate'
      preLoaderRoute: typeof ApiPluginsDeprecateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/delete': {
      id: '/api/plugins/delete'
      path: '/api/plugins/delete'
      fullPath: '/api/plugins/delete'
      preLoaderRoute: typeof ApiPluginsDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/create': {
      id: '/api/plugins/create'
      path: '/api/plugins/create'
      fullPath: '/api/plugins/create'
      preLoaderRoute: typeof ApiPluginsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/scopes': {
      id: '/api/operator/scopes'
      path: '/api/operator/scopes'
      fullPath: '/api/operator/scopes'
      preLoaderRoute: typeof ApiOperatorScopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/reports': {
      id: '/api/operator/reports'
      path: '/api/operator/reports'
      fullPath: '/api/operator/reports'
      preLoaderRoute: typeof ApiOperatorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/plugins': {
      id: '/api/operator/plugins'
      path: '/api/operator/plugins'
      fullPath: '/api/operator/plugins'
      preLoaderRoute: typeof ApiOperatorPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/audit': {
      id: '/api/operator/audit'
      path: '/api/operator/audit'
      fullPath: '/api/operator/audit'
      preLoaderRoute: typeof ApiOperatorAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/approve': {
      id: '/api/device/approve'
      path: '/api/device/approve'
      fullPath: '/api/device/approve'
      preLoaderRoute: typeof ApiDeviceApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/tokens': {
      id: '/api/account/tokens'
      path: '/api/account/tokens'
      fullPath: '/api/account/tokens'
      preLoaderRoute: typeof ApiAccountTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/profile': {
      id: '/api/account/profile'
      path: '/api/account/profile'
      fullPath: '/api/account/profile'
      preLoaderRoute: typeof ApiAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/avatar': {
      id: '/api/account/avatar'
      path: '/api/account/avatar'
      fullPath: '/api/account/avatar'
      preLoaderRoute: typeof ApiAccountAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/activity': {
      id: '/api/account/activity'
      path: '/api/account/activity'
      fullPath: '/api/account/activity'
      preLoaderRoute: typeof ApiAccountActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/plugins/$name/versions': {
      id: '/v1/plugins/$name/versions'
      path: '/versions'
      fullPath: '/v1/plugins/$name/versions'
      preLoaderRoute: typeof V1PluginsNameVersionsRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/reviews': {
      id: '/v1/plugins/$name/reviews'
      path: '/reviews'
      fullPath: '/v1/plugins/$name/reviews'
      preLoaderRoute: typeof V1PluginsNameReviewsRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/reports': {
      id: '/v1/plugins/$name/reports'
      path: '/reports'
      fullPath: '/v1/plugins/$name/reports'
      preLoaderRoute: typeof V1PluginsNameReportsRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/readme': {
      id: '/v1/plugins/$name/readme'
      path: '/readme'
      fullPath: '/v1/plugins/$name/readme'
      preLoaderRoute: typeof V1PluginsNameReadmeRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/comments': {
      id: '/v1/plugins/$name/comments'
      path: '/comments'
      fullPath: '/v1/plugins/$name/comments'
      preLoaderRoute: typeof V1PluginsNameCommentsRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/api/scopes/$scope/trusted-publishers': {
      id: '/api/scopes/$scope/trusted-publishers'
      path: '/trusted-publishers'
      fullPath: '/api/scopes/$scope/trusted-publishers'
      preLoaderRoute: typeof ApiScopesScopeTrustedPublishersRouteImport
      parentRoute: typeof ApiScopesScopeRoute
    }
    '/api/scopes/$scope/profile': {
      id: '/api/scopes/$scope/profile'
      path: '/profile'
      fullPath: '/api/scopes/$scope/profile'
      preLoaderRoute: typeof ApiScopesScopeProfileRouteImport
      parentRoute: typeof ApiScopesScopeRoute
    }
    '/api/scopes/$scope/members': {
      id: '/api/scopes/$scope/members'
      path: '/members'
      fullPath: '/api/scopes/$scope/members'
      preLoaderRoute: typeof ApiScopesScopeMembersRouteImport
      parentRoute: typeof ApiScopesScopeRoute
    }
    '/api/scopes/$scope/icon': {
      id: '/api/scopes/$scope/icon'
      path: '/icon'
      fullPath: '/api/scopes/$scope/icon'
      preLoaderRoute: typeof ApiScopesScopeIconRouteImport
      parentRoute: typeof ApiScopesScopeRoute
    }
    '/api/scopes/$scope/domains': {
      id: '/api/scopes/$scope/domains'
      path: '/domains'
      fullPath: '/api/scopes/$scope/domains'
      preLoaderRoute: typeof ApiScopesScopeDomainsRouteImport
      parentRoute: typeof ApiScopesScopeRoute
    }
    '/api/scopes/$scope/display-name': {
      id: '/api/scopes/$scope/display-name'
      path: '/display-name'
      fullPath: '/api/scopes/$scope/display-name'
      preLoaderRoute: typeof ApiScopesScopeDisplayNameRouteImport
      parentRoute: typeof ApiScopesScopeRoute
    }
    '/api/operator/reports/update': {
      id: '/api/operator/reports/update'
      path: '/update'
      fullPath: '/api/operator/reports/update'
      preLoaderRoute: typeof ApiOperatorReportsUpdateRouteImport
      parentRoute: typeof ApiOperatorReportsRoute
    }
    '/api/operator/plugins/versions': {
      id: '/api/operator/plugins/versions'
      path: '/versions'
      fullPath: '/api/operator/plugins/versions'
      preLoaderRoute: typeof ApiOperatorPluginsVersionsRouteImport
      parentRoute: typeof ApiOperatorPluginsRoute
    }
    '/api/operator/plugins/verify': {
      id: '/api/operator/plugins/verify'
      path: '/verify'
      fullPath: '/api/operator/plugins/verify'
      preLoaderRoute: typeof ApiOperatorPluginsVerifyRouteImport
      parentRoute: typeof ApiOperatorPluginsRoute
    }
    '/api/operator/plugins/takedown': {
      id: '/api/operator/plugins/takedown'
      path: '/takedown'
      fullPath: '/api/operator/plugins/takedown'
      preLoaderRoute: typeof ApiOperatorPluginsTakedownRouteImport
      parentRoute: typeof ApiOperatorPluginsRoute
    }
    '/api/operator/plugins/restore': {
      id: '/api/operator/plugins/restore'
      path: '/restore'
      fullPath: '/api/operator/plugins/restore'
      preLoaderRoute: typeof ApiOperatorPluginsRestoreRouteImport
      parentRoute: typeof ApiOperatorPluginsRoute
    }
    '/api/operator/plugins/plugin-restore': {
      id: '/api/operator/plugins/plugin-restore'
      path: '/plugin-restore'
      fullPath: '/api/operator/plugins/plugin-restore'
      preLoaderRoute: typeof ApiOperatorPluginsPluginRestoreRouteImport
      parentRoute: typeof ApiOperatorPluginsRoute
    }
    '/api/operator/plugins/bulk-takedown': {
      id: '/api/operator/plugins/bulk-takedown'
      path: '/bulk-takedown'
      fullPath: '/api/operator/plugins/bulk-takedown'
      preLoaderRoute: typeof ApiOperatorPluginsBulkTakedownRouteImport
      parentRoute: typeof ApiOperatorPluginsRoute
    }
    '/api/account/tokens/$hash': {
      id: '/api/account/tokens/$hash'
      path: '/$hash'
      fullPath: '/api/account/tokens/$hash'
      preLoaderRoute: typeof ApiAccountTokensHashRouteImport
      parentRoute: typeof ApiAccountTokensRoute
    }
    '/api/scopes/$scope/members/$memberId': {
      id: '/api/scopes/$scope/members/$memberId'
      path: '/$memberId'
      fullPath: '/api/scopes/$scope/members/$memberId'
      preLoaderRoute: typeof ApiScopesScopeMembersMemberIdRouteImport
      parentRoute: typeof ApiScopesScopeMembersRoute
    }
    '/api/operator/scopes/$scope/verify': {
      id: '/api/operator/scopes/$scope/verify'
      path: '/$scope/verify'
      fullPath: '/api/operator/scopes/$scope/verify'
      preLoaderRoute: typeof ApiOperatorScopesScopeVerifyRouteImport
      parentRoute: typeof ApiOperatorScopesRoute
    }
    '/api/operator/scopes/$scope/takedown': {
      id: '/api/operator/scopes/$scope/takedown'
      path: '/$scope/takedown'
      fullPath: '/api/operator/scopes/$scope/takedown'
      preLoaderRoute: typeof ApiOperatorScopesScopeTakedownRouteImport
      parentRoute: typeof ApiOperatorScopesRoute
    }
    '/api/operator/scopes/$scope/restore': {
      id: '/api/operator/scopes/$scope/restore'
      path: '/$scope/restore'
      fullPath: '/api/operator/scopes/$scope/restore'
      preLoaderRoute: typeof ApiOperatorScopesScopeRestoreRouteImport
      parentRoute: typeof ApiOperatorScopesRoute
    }
    '/v1/plugins/$name/v/$version/index': {
      id: '/v1/plugins/$name/v/$version/index'
      path: '/v/$version/index'
      fullPath: '/v1/plugins/$name/v/$version/index'
      preLoaderRoute: typeof V1PluginsNameVVersionChar91indexChar93RouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
    '/v1/plugins/$name/reviews/$reviewId/vote': {
      id: '/v1/plugins/$name/reviews/$reviewId/vote'
      path: '/$reviewId/vote'
      fullPath: '/v1/plugins/$name/reviews/$reviewId/vote'
      preLoaderRoute: typeof V1PluginsNameReviewsReviewIdVoteRouteImport
      parentRoute: typeof V1PluginsNameReviewsRoute
    }
    '/v1/plugins/$name/comments/$commentId/vote': {
      id: '/v1/plugins/$name/comments/$commentId/vote'
      path: '/$commentId/vote'
      fullPath: '/v1/plugins/$name/comments/$commentId/vote'
      preLoaderRoute: typeof V1PluginsNameCommentsCommentIdVoteRouteImport
      parentRoute: typeof V1PluginsNameCommentsRoute
    }
    '/v1/plugins/$name/v/$version/files/$': {
      id: '/v1/plugins/$name/v/$version/files/$'
      path: '/v/$version/files/$'
      fullPath: '/v1/plugins/$name/v/$version/files/$'
      preLoaderRoute: typeof V1PluginsNameVVersionFilesSplatRouteImport
      parentRoute: typeof V1PluginsNameRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardScopesRoute: typeof DashboardScopesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountTokensRoute: typeof DashboardAccountTokensRoute
  DashboardPluginsSplatRoute: typeof DashboardPluginsSplatRoute
  DashboardPluginsCreateRoute: typeof DashboardPluginsCreateRoute
  DashboardScopesScopeRoute: typeof DashboardScopesScopeRoute
  DashboardPluginsIndexRoute: typeof DashboardPluginsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardScopesRoute: DashboardScopesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountTokensRoute: DashboardAccountTokensRoute,
  DashboardPluginsSplatRoute: DashboardPluginsSplatRoute,
  DashboardPluginsCreateRoute: DashboardPluginsCreateRoute,
  DashboardScopesScopeRoute: DashboardScopesScopeRoute,
  DashboardPluginsIndexRoute: DashboardPluginsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OperatorRouteChildren {
  OperatorAuditRoute: typeof OperatorAuditRoute
  OperatorPluginsRoute: typeof OperatorPluginsRoute
  OperatorReportsRoute: typeof OperatorReportsRoute
  OperatorScopesRoute: typeof OperatorScopesRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorAuditRoute: OperatorAuditRoute,
  OperatorPluginsRoute: OperatorPluginsRoute,
  OperatorReportsRoute: OperatorReportsRoute,
  OperatorScopesRoute: OperatorScopesRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface ApiScopesScopeMembersRouteChildren {
  ApiScopesScopeMembersMemberIdRoute: typeof ApiScopesScopeMembersMemberIdRoute
}

const ApiScopesScopeMembersRouteChildren: ApiScopesScopeMembersRouteChildren = {
  ApiScopesScopeMembersMemberIdRoute: ApiScopesScopeMembersMemberIdRoute,
}

const ApiScopesScopeMembersRouteWithChildren =
  ApiScopesScopeMembersRoute._addFileChildren(
    ApiScopesScopeMembersRouteChildren,
  )

interface ApiScopesScopeRouteChildren {
  ApiScopesScopeDisplayNameRoute: typeof ApiScopesScopeDisplayNameRoute
  ApiScopesScopeDomainsRoute: typeof ApiScopesScopeDomainsRoute
  ApiScopesScopeIconRoute: typeof ApiScopesScopeIconRoute
  ApiScopesScopeMembersRoute: typeof ApiScopesScopeMembersRouteWithChildren
  ApiScopesScopeProfileRoute: typeof ApiScopesScopeProfileRoute
  ApiScopesScopeTrustedPublishersRoute: typeof ApiScopesScopeTrustedPublishersRoute
}

const ApiScopesScopeRouteChildren: ApiScopesScopeRouteChildren = {
  ApiScopesScopeDisplayNameRoute: ApiScopesScopeDisplayNameRoute,
  ApiScopesScopeDomainsRoute: ApiScopesScopeDomainsRoute,
  ApiScopesScopeIconRoute: ApiScopesScopeIconRoute,
  ApiScopesScopeMembersRoute: ApiScopesScopeMembersRouteWithChildren,
  ApiScopesScopeProfileRoute: ApiScopesScopeProfileRoute,
  ApiScopesScopeTrustedPublishersRoute: ApiScopesScopeTrustedPublishersRoute,
}

const ApiScopesScopeRouteWithChildren = ApiScopesScopeRoute._addFileChildren(
  ApiScopesScopeRouteChildren,
)

interface ApiScopesRouteChildren {
  ApiScopesScopeRoute: typeof ApiScopesScopeRouteWithChildren
}

const ApiScopesRouteChildren: ApiScopesRouteChildren = {
  ApiScopesScopeRoute: ApiScopesScopeRouteWithChildren,
}

const ApiScopesRouteWithChildren = ApiScopesRoute._addFileChildren(
  ApiScopesRouteChildren,
)

interface ApiAccountTokensRouteChildren {
  ApiAccountTokensHashRoute: typeof ApiAccountTokensHashRoute
}

const ApiAccountTokensRouteChildren: ApiAccountTokensRouteChildren = {
  ApiAccountTokensHashRoute: ApiAccountTokensHashRoute,
}

const ApiAccountTokensRouteWithChildren =
  ApiAccountTokensRoute._addFileChildren(ApiAccountTokensRouteChildren)

interface ApiOperatorPluginsRouteChildren {
  ApiOperatorPluginsBulkTakedownRoute: typeof ApiOperatorPluginsBulkTakedownRoute
  ApiOperatorPluginsPluginRestoreRoute: typeof ApiOperatorPluginsPluginRestoreRoute
  ApiOperatorPluginsRestoreRoute: typeof ApiOperatorPluginsRestoreRoute
  ApiOperatorPluginsTakedownRoute: typeof ApiOperatorPluginsTakedownRoute
  ApiOperatorPluginsVerifyRoute: typeof ApiOperatorPluginsVerifyRoute
  ApiOperatorPluginsVersionsRoute: typeof ApiOperatorPluginsVersionsRoute
}

const ApiOperatorPluginsRouteChildren: ApiOperatorPluginsRouteChildren = {
  ApiOperatorPluginsBulkTakedownRoute: ApiOperatorPluginsBulkTakedownRoute,
  ApiOperatorPluginsPluginRestoreRoute: ApiOperatorPluginsPluginRestoreRoute,
  ApiOperatorPluginsRestoreRoute: ApiOperatorPluginsRestoreRoute,
  ApiOperatorPluginsTakedownRoute: ApiOperatorPluginsTakedownRoute,
  ApiOperatorPluginsVerifyRoute: ApiOperatorPluginsVerifyRoute,
  ApiOperatorPluginsVersionsRoute: ApiOperatorPluginsVersionsRoute,
}

const ApiOperatorPluginsRouteWithChildren =
  ApiOperatorPluginsRoute._addFileChildren(ApiOperatorPluginsRouteChildren)

interface ApiOperatorReportsRouteChildren {
  ApiOperatorReportsUpdateRoute: typeof ApiOperatorReportsUpdateRoute
}

const ApiOperatorReportsRouteChildren: ApiOperatorReportsRouteChildren = {
  ApiOperatorReportsUpdateRoute: ApiOperatorReportsUpdateRoute,
}

const ApiOperatorReportsRouteWithChildren =
  ApiOperatorReportsRoute._addFileChildren(ApiOperatorReportsRouteChildren)

interface ApiOperatorScopesRouteChildren {
  ApiOperatorScopesScopeRestoreRoute: typeof ApiOperatorScopesScopeRestoreRoute
  ApiOperatorScopesScopeTakedownRoute: typeof ApiOperatorScopesScopeTakedownRoute
  ApiOperatorScopesScopeVerifyRoute: typeof ApiOperatorScopesScopeVerifyRoute
}

const ApiOperatorScopesRouteChildren: ApiOperatorScopesRouteChildren = {
  ApiOperatorScopesScopeRestoreRoute: ApiOperatorScopesScopeRestoreRoute,
  ApiOperatorScopesScopeTakedownRoute: ApiOperatorScopesScopeTakedownRoute,
  ApiOperatorScopesScopeVerifyRoute: ApiOperatorScopesScopeVerifyRoute,
}

const ApiOperatorScopesRouteWithChildren =
  ApiOperatorScopesRoute._addFileChildren(ApiOperatorScopesRouteChildren)

interface V1PluginsNameCommentsRouteChildren {
  V1PluginsNameCommentsCommentIdVoteRoute: typeof V1PluginsNameCommentsCommentIdVoteRoute
}

const V1PluginsNameCommentsRouteChildren: V1PluginsNameCommentsRouteChildren = {
  V1PluginsNameCommentsCommentIdVoteRoute:
    V1PluginsNameCommentsCommentIdVoteRoute,
}

const V1PluginsNameCommentsRouteWithChildren =
  V1PluginsNameCommentsRoute._addFileChildren(
    V1PluginsNameCommentsRouteChildren,
  )

interface V1PluginsNameReviewsRouteChildren {
  V1PluginsNameReviewsReviewIdVoteRoute: typeof V1PluginsNameReviewsReviewIdVoteRoute
}

const V1PluginsNameReviewsRouteChildren: V1PluginsNameReviewsRouteChildren = {
  V1PluginsNameReviewsReviewIdVoteRoute: V1PluginsNameReviewsReviewIdVoteRoute,
}

const V1PluginsNameReviewsRouteWithChildren =
  V1PluginsNameReviewsRoute._addFileChildren(V1PluginsNameReviewsRouteChildren)

interface V1PluginsNameRouteChildren {
  V1PluginsNameCommentsRoute: typeof V1PluginsNameCommentsRouteWithChildren
  V1PluginsNameReadmeRoute: typeof V1PluginsNameReadmeRoute
  V1PluginsNameReportsRoute: typeof V1PluginsNameReportsRoute
  V1PluginsNameReviewsRoute: typeof V1PluginsNameReviewsRouteWithChildren
  V1PluginsNameVersionsRoute: typeof V1PluginsNameVersionsRoute
  V1PluginsNameVVersionChar91indexChar93Route: typeof V1PluginsNameVVersionChar91indexChar93Route
  V1PluginsNameVVersionFilesSplatRoute: typeof V1PluginsNameVVersionFilesSplatRoute
}

const V1PluginsNameRouteChildren: V1PluginsNameRouteChildren = {
  V1PluginsNameCommentsRoute: V1PluginsNameCommentsRouteWithChildren,
  V1PluginsNameReadmeRoute: V1PluginsNameReadmeRoute,
  V1PluginsNameReportsRoute: V1PluginsNameReportsRoute,
  V1PluginsNameReviewsRoute: V1PluginsNameReviewsRouteWithChildren,
  V1PluginsNameVersionsRoute: V1PluginsNameVersionsRoute,
  V1PluginsNameVVersionChar91indexChar93Route:
    V1PluginsNameVVersionChar91indexChar93Route,
  V1PluginsNameVVersionFilesSplatRoute: V1PluginsNameVVersionFilesSplatRoute,
}

const V1PluginsNameRouteWithChildren = V1PluginsNameRoute._addFileChildren(
  V1PluginsNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRouteWithChildren,
  ApiScopesRoute: ApiScopesRouteWithChildren,
  AssetsSplatRoute: AssetsSplatRoute,
  AuthGithubRoute: AuthGithubRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthMeRoute: AuthMeRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalLicensesRoute: LegalLicensesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  UIdRoute: UIdRoute,
  V1RegistryRoute: V1RegistryRoute,
  V1SearchRoute: V1SearchRoute,
  V1VerifiedRoute: V1VerifiedRoute,
  LegalIndexRoute: LegalIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  ApiAccountActivityRoute: ApiAccountActivityRoute,
  ApiAccountAvatarRoute: ApiAccountAvatarRoute,
  ApiAccountProfileRoute: ApiAccountProfileRoute,
  ApiAccountTokensRoute: ApiAccountTokensRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDeviceApproveRoute: ApiDeviceApproveRoute,
  ApiOperatorAuditRoute: ApiOperatorAuditRoute,
  ApiOperatorPluginsRoute: ApiOperatorPluginsRouteWithChildren,
  ApiOperatorReportsRoute: ApiOperatorReportsRouteWithChildren,
  ApiOperatorScopesRoute: ApiOperatorScopesRouteWithChildren,
  ApiPluginsCreateRoute: ApiPluginsCreateRoute,
  ApiPluginsDeleteRoute: ApiPluginsDeleteRoute,
  ApiPluginsDeprecateRoute: ApiPluginsDeprecateRoute,
  ApiPluginsMineRoute: ApiPluginsMineRoute,
  ApiPluginsVersionsRoute: ApiPluginsVersionsRoute,
  ApiPluginsYankRoute: ApiPluginsYankRoute,
  V1PluginsNameRoute: V1PluginsNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
