#!/usr/bin/env bun
/**
 * Generate apps/web/src/i18n/locales/en/index.ts (the typed catalog barrel) from the `en/*.json`
 * namespace files. The barrel is the only place TS can learn the literal `"namespace:key"` union
 * (`import.meta.glob` types every module as the same wide `Record`), so `AppCatalog`/`AppKey` track
 * it automatically. Run `bun run i18n:barrel` after adding or removing a namespace; `--check` (run in
 * `lint`) fails if the committed barrel is stale, so it can never silently drift from the JSON.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { Glob } from "bun";

const CHECK = process.argv.includes("--check");
const DIR = "apps/web/src/i18n/locales/en";
const BARREL = `${DIR}/index.ts`;

const names = [...new Glob(`${DIR}/*.json`).scanSync(".")]
  .map((path) => path.slice(path.lastIndexOf("/") + 1, -".json".length))
  .sort();

const invalid = names.filter((name) => !/^[a-zA-Z_$][\w$]*$/.test(name));
if (invalid.length > 0) {
  console.error(`i18n:barrel: namespace files are not valid identifiers: ${invalid.join(", ")}`);
  console.error("Rename them to camelCase (e.g. plugin-detail.json -> pluginDetail.json).");
  process.exit(1);
}

const content = `${[
  "// GENERATED by scripts/gen-i18n-barrel.ts from en/*.json. Do not edit by hand; run `bun run i18n:barrel`.",
  ...names.map((name) => `import ${name} from "./${name}.json";`),
  "",
  "/** The English catalog as a typed value: the source of truth for message keys (see `@/i18n`). */",
  "export default {",
  ...names.map((name) => `  ${name},`),
  "} as const;",
].join("\n")}\n`;

if (CHECK) {
  if (readFileSync(BARREL, "utf8") !== content) {
    console.error(`${BARREL} is stale. Run \`bun run i18n:barrel\` and commit.`);
    process.exit(1);
  }
  console.log(`i18n:barrel: ${BARREL} is up to date (${names.length} namespaces).`);
} else {
  writeFileSync(BARREL, content);
  console.log(`i18n:barrel: wrote ${BARREL} (${names.length} namespaces).`);
}
