#!/usr/bin/env bun
/**
 * Generate docs/specs/INDEX.md from the per-spec frontmatter. The index is a build
 * artifact, never hand-edited, so it cannot drift from the specs. Run after adding or
 * editing a spec: `bun run spec:index` (or `spec:check` runs index + coverage).
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs, ROOT, STATUS_LABEL, type Status } from "./spec-lib";

const specs = loadSpecs();

const counts: Record<Status, number> = { done: 0, wip: 0, todo: 0, hold: 0, gone: 0 };
let acTotal = 0;
for (const s of specs) {
  counts[s.status]++;
  acTotal += s.criteria.length;
}

// INDEX.md lives in docs/specs/, so link to spec files relative to that dir.
const link = (s: { id: string; file: string }) =>
  `[${s.id}](${s.file.replace("docs/specs/", "")})`;
const row = (s: (typeof specs)[number]) =>
  `| ${link(s)} | ${STATUS_LABEL[s.status]} | ${s.title} |`;

const byGroup = new Map<string, typeof specs>();
for (const s of specs) byGroup.set(s.group, [...(byGroup.get(s.group) ?? []), s]);

const backlog = specs.filter((s) => s.status !== "done" && s.status !== "gone");

const out: string[] = [];
out.push("<!-- GENERATED by scripts/gen-spec-index.ts. Do not edit by hand. -->");
out.push("# Spec index\n");
out.push(
  "The generated register of every Brika spec. Run `bun run spec:index` to regenerate,",
);
out.push("`bun run spec:coverage` to see which criteria have tests citing their code.\n");
out.push("## Totals\n");
out.push(`${specs.length} specs , ${acTotal} acceptance criteria.\n`);
out.push("| Status | Count |");
out.push("| --- | --- |");
out.push(`| [DONE] | ${counts.done} |`);
out.push(`| [WIP] | ${counts.wip} |`);
out.push(`| [TODO] | ${counts.todo} |`);
out.push(`| [HOLD] | ${counts.hold} |`);
if (counts.gone > 0) out.push(`| [GONE] | ${counts.gone} |`);
out.push("");

out.push("## Backlog (not done)\n");
out.push("| Code | Status | Title |");
out.push("| --- | --- | --- |");
for (const s of backlog) out.push(row(s));
out.push("");

for (const [group, list] of [...byGroup].sort()) {
  out.push(`## ${group}\n`);
  out.push("| Code | Status | Title |");
  out.push("| --- | --- | --- |");
  for (const s of list) out.push(row(s));
  out.push("");
}

writeFileSync(join(ROOT, "docs/specs/INDEX.md"), `${out.join("\n")}\n`);
console.log(`Wrote docs/specs/INDEX.md (${specs.length} specs).`);
